"""Feature attribution, SHAP decomposition, and Tactical 9-Grid schemas."""

from enum import Enum
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field


class QuadrantEnum(str, Enum):
    """The 9 exact quadrants of the EA Tactical 9-Grid Attribution Matrix."""
    GOLD_MINES = "GOLD_MINES"                # High ROAS, Low Frequency -> Scale Up
    CORE_DRIVERS = "CORE_DRIVERS"            # High ROAS, Medium Frequency -> Maintain
    SATURATED_STARS = "SATURATED_STARS"      # High ROAS, High Frequency -> Monitor / Retire
    UNTAPPED = "UNTAPPED"                    # Medium ROAS, Low Frequency -> Test More
    WORKHORSES = "WORKHORSES"                # Medium ROAS, Medium Frequency -> Optimize
    EFFICIENCY_RISKS = "EFFICIENCY_RISKS"    # Medium ROAS, High Frequency -> Trim Budget
    NOISE = "NOISE"                          # Low ROAS, Low Frequency -> Discard
    UNDERPERFORMERS = "UNDERPERFORMERS"      # Low ROAS, Medium Frequency -> Pivot Creative
    MONEY_PITS = "MONEY_PITS"                # Low ROAS, High Frequency -> Kill Immediately


class Tactical9GridPoint(BaseModel):
    """A feature positioned in the Tactical 9-Grid coordinate space."""
    feature_name: str = Field(..., description="Name of creative feature, mechanic, or surface")
    feature_type: str = Field(
        ..., description="'game_mechanic', 'visual_hook', 'audio_cue', 'surface', or 'pacing'"
    )
    frequency_x: float = Field(
        ..., description="Occurrence frequency / campaign exposure count (X-axis)"
    )
    roas_impact_y: float = Field(
        ..., description="Marginal SHAP ROAS contribution multiplier (Y-axis)"
    )
    quadrant: QuadrantEnum = Field(..., description="Assigned 9-Grid quadrant")
    strategic_action: str = Field(
        ..., description="Recommended strategic directive (Scale Up, Maintain, etc.)"
    )
    confidence: float = Field(default=0.92, ge=0.0, le=1.0)
    sample_campaigns_count: int = Field(default=12, ge=1)
    franchise: str = Field(default="Apex Legends")


class SHAPFeatureContribution(BaseModel):
    """Decomposed SHAP marginal contribution for a single feature."""
    feature_name: str
    shap_value: float = Field(..., description="Additive marginal contribution to target metric")
    feature_value: float = Field(..., description="Observed feature value or binary activation")
    baseline_value: float = Field(default=1.0, description="Expected value / baseline")
    relative_importance_pct: float = Field(
        ..., description="Percentage of total positive/negative model attribution"
    )
    direction: str = Field(..., description="'POSITIVE' or 'NEGATIVE'")


class TacticalGridResponse(BaseModel):
    """Full tactical 9-grid payload for UI rendering and agent analysis."""
    model_id: str
    campaign_id: str
    franchise: str
    features: List[Tactical9GridPoint]
    quadrant_counts: Dict[str, int]
    avg_marginal_roas: float
    top_driver_feature: str
    top_risk_feature: str
    generated_at: str


class AttributionExplainRequest(BaseModel):
    """Request for Gemini 3.6 Flash (thinking_level=HIGH) chain-of-thought analysis."""
    campaign_id: str = Field(default="camp-apex-s22-relaunch")
    franchise: str = Field(default="Apex Legends")
    target_metric: str = Field(default="D7 ROAS")
    features: Optional[List[Tactical9GridPoint]] = None
    custom_context: Optional[str] = None


class RecommendationAction(BaseModel):
    """Actionable creative or media buying directive."""
    action_type: str = Field(..., description="'CREATIVE_REVISION', 'BUDGET_REALLOCATION', 'CHANNEL_TEST'")
    feature_name: str
    quadrant: QuadrantEnum
    priority: str = Field(..., description="'P0_CRITICAL', 'P1_HIGH', 'P2_MEDIUM'")
    recommendation_text: str
    expected_roas_delta: float


class AttributionExplainResponse(BaseModel):
    """Deep CoT explanation generated by Gemini 3.6 Flash."""
    campaign_id: str
    franchise: str
    executive_summary: str
    chain_of_thought_reasoning: List[str] = Field(
        ..., description="Step-by-step analytical reasoning from high thinking level"
    )
    quadrant_breakdowns: Dict[str, str]
    key_recommendations: List[RecommendationAction]
    model_used: str = "gemini-3.6-flash (thinking_level=HIGH)"
    generated_at: str
