import { Franchise, EASurface, TacticalQuadrant, GeoSpineMetro, NielsenDMA, WeatherTrajectoryPoint } from '@/types';

export const TWO_K_FRANCHISES: Franchise[] = [
  'NBA 2K26',
  'Borderlands 4',
  "Sid Meier's Civilization VII",
  'WWE 2K25',
  'PGA TOUR 2K25',
];

export const EA_FRANCHISES: Franchise[] = TWO_K_FRANCHISES;

export const TWO_K_SURFACES: { id: EASurface; label: string; description: string }[] = [
  { id: 'THE_CITY_BILLBOARDS', label: 'The City Dynamic Billboards', description: 'Open-world streetball & neon boulevard high-impact LED displays' },
  { id: 'ARENA_JUMBOTRON', label: 'Arena Jumbotron & Ribbon', description: 'Court-side 360 LED ribbon & center-hung 8K scoreboard takeovers' },
  { id: 'MYCAREER_PAUSE', label: 'MyCAREER Tactical Pause', description: 'Contextual timeout, halftime & post-game brand sponsor cards' },
  { id: 'MYTEAM_APP', label: 'MyTEAM Mobile Companion', description: 'Pack drop push alerts & auction house real-time banner promos' },
  { id: '2K_HUB_LAUNCHER', label: '2K Hub Launcher', description: 'Cross-franchise launcher hero banner & seasonal pre-order carousel' },
  { id: 'STREAMING_OVERLAYS', label: 'Twitch & 2K League Drops', description: 'Interactive broadcast viewer quest overlays & locker code popups' },
];

export const EA_SURFACES = TWO_K_SURFACES;


export const TACTICAL_QUADRANTS: {
  id: TacticalQuadrant;
  name: string;
  action: string;
  color: string;
  badgeBg: string;
  borderColor: string;
  description: string;
}[] = [
  {
    id: 'GOLD_MINES',
    name: 'Gold Mines',
    action: 'Scale Up',
    color: '#00C48C',
    badgeBg: 'rgba(0, 196, 140, 0.15)',
    borderColor: '#00C48C',
    description: 'High marginal ROAS impact with low market saturation. Prime candidates for aggressive spend scaling.',
  },
  {
    id: 'CORE_DRIVERS',
    name: 'Core Drivers',
    action: 'Maintain & Protect',
    color: '#0072BC',
    badgeBg: 'rgba(0, 114, 188, 0.15)',
    borderColor: '#0072BC',
    description: 'High ROAS impact with healthy, sustainable occurrence frequency. Keep active as campaign anchors.',
  },
  {
    id: 'SATURATED_STARS',
    name: 'Saturated Stars',
    action: 'Monitor / Rotate',
    color: '#FFB800',
    badgeBg: 'rgba(255, 184, 0, 0.15)',
    borderColor: '#FFB800',
    description: 'High historic ROAS but nearing creative fatigue / diminishing marginal returns. Prepare creative refreshes.',
  },
  {
    id: 'UNTAPPED',
    name: 'Untapped Potential',
    action: 'Test & Expand',
    color: '#38BDF8',
    badgeBg: 'rgba(56, 189, 248, 0.15)',
    borderColor: '#38BDF8',
    description: 'Moderate ROAS with low frequency. Increase testing budget to measure true saturation curve slope.',
  },
  {
    id: 'WORKHORSES',
    name: 'Workhorses',
    action: 'Optimize Pacing',
    color: '#8A2BE2',
    badgeBg: 'rgba(138, 43, 226, 0.15)',
    borderColor: '#8A2BE2',
    description: 'Steady average ROAS and consistent frequency. Optimize copy and audio hooks to boost lift.',
  },
  {
    id: 'EFFICIENCY_RISKS',
    name: 'Efficiency Risks',
    action: 'Trim Budget',
    color: '#FB923C',
    badgeBg: 'rgba(251, 146, 60, 0.15)',
    borderColor: '#FB923C',
    description: 'Moderate ROAS heavily diluted by excessive frequency. Trim spend to move back up the marginal Hill curve.',
  },
  {
    id: 'NOISE',
    name: 'Noise / Inconclusive',
    action: 'Discard / Deprecate',
    color: '#8FA3BC',
    badgeBg: 'rgba(143, 163, 188, 0.15)',
    borderColor: '#8FA3BC',
    description: 'Low ROAS and low frequency. Statistical noise with zero clear causal lift. Discard from tag library.',
  },
  {
    id: 'UNDERPERFORMERS',
    name: 'Underperformers',
    action: 'Pivot Creative Hook',
    color: '#FF4560',
    badgeBg: 'rgba(255, 69, 96, 0.15)',
    borderColor: '#FF4560',
    description: 'Low marginal ROAS despite moderate test frequency. Radical creative revision or voiceover pivot needed.',
  },
  {
    id: 'MONEY_PITS',
    name: 'Money Pits',
    action: 'Kill Immediately',
    color: '#FF4560',
    badgeBg: 'rgba(255, 69, 96, 0.25)',
    borderColor: '#FF4560',
    description: 'Severe negative marginal ROAS with high ongoing spend. Halt media buys immediately to prevent budget bleed.',
  },
];

export const EXECUTIVE_BENCHMARKS = [
  {
    company: 'Netmarble',
    metric: '+640% ROAS',
    subtitle: 'tROAS & Audience Signal Bidding',
    description: 'Demonstrated massive top-line surge by replacing manual channel buying with Meridian MMM Bayesian prior tuning.',
    icon: 'TrendingUp',
    color: '#00C48C',
  },
  {
    company: 'Hitapps',
    metric: '6% → 30% D7 ROAS',
    subtitle: '7.7x Daily Revenue in 4 Months',
    description: 'Scaled cross-surface campaigns with real-time predictive saturation pacing and automated feature attribution.',
    icon: 'Zap',
    color: '#0072BC',
  },
  {
    company: 'SuperPlay',
    metric: '>100% ROAS Cohorts',
    subtitle: '+38% Higher D30 ARPU',
    description: 'Integrated synthetic gamer persona simulations (BARE pattern) to eliminate pre-spend monetization friction.',
    icon: 'Target',
    color: '#FFB800',
  },
  {
    company: 'InnoGames',
    metric: '-85% Android CPI',
    subtitle: 'Automated Creative Intelligence',
    description: 'Decoupled video storybeats and game mechanics with Gemini multimodal frame extraction to eliminate creative waste.',
    icon: 'ShieldCheck',
    color: '#8A2BE2',
  },
];

export const US_25_METROS: GeoSpineMetro[] = [
  {
    criteria_id: 21149,
    metro_name: 'New York NY',
    state: 'NY',
    lat: 40.7128,
    lng: -74.0060,
    gamer_population: 4850000,
    population_density_sq_km: 10800,
    trends_index: 94,
    weather_shock_temp_c: -3.2,
    weather_shock_precip_mm: 18.5,
    hill_parameters: { base_roas: 2.85, half_saturation_s: 420, shape_k: 1.45 },
    predicted_cpi: 4.80,
    predicted_roas: 2.65,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21175,
    metro_name: 'Los Angeles CA',
    state: 'CA',
    lat: 34.0522,
    lng: -118.2437,
    gamer_population: 4120000,
    population_density_sq_km: 3200,
    trends_index: 98,
    weather_shock_temp_c: 1.4,
    weather_shock_precip_mm: 0.0,
    hill_parameters: { base_roas: 3.10, half_saturation_s: 390, shape_k: 1.55 },
    predicted_cpi: 5.15,
    predicted_roas: 2.92,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21160,
    metro_name: 'Chicago IL',
    state: 'IL',
    lat: 41.8781,
    lng: -87.6298,
    gamer_population: 2650000,
    population_density_sq_km: 4600,
    trends_index: 86,
    weather_shock_temp_c: -6.8,
    weather_shock_precip_mm: 32.1,
    hill_parameters: { base_roas: 2.70, half_saturation_s: 310, shape_k: 1.38 },
    predicted_cpi: 4.10,
    predicted_roas: 2.80,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21162,
    metro_name: 'Dallas-Ft. Worth TX',
    state: 'TX',
    lat: 32.7767,
    lng: -96.7970,
    gamer_population: 2340000,
    population_density_sq_km: 1500,
    trends_index: 91,
    weather_shock_temp_c: 4.5,
    weather_shock_precip_mm: 5.2,
    hill_parameters: { base_roas: 2.95, half_saturation_s: 290, shape_k: 1.50 },
    predicted_cpi: 3.95,
    predicted_roas: 3.05,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21147,
    metro_name: 'Philadelphia PA',
    state: 'PA',
    lat: 39.9526,
    lng: -75.1652,
    gamer_population: 1820000,
    population_density_sq_km: 4500,
    trends_index: 82,
    weather_shock_temp_c: -2.1,
    weather_shock_precip_mm: 12.0,
    hill_parameters: { base_roas: 2.50, half_saturation_s: 240, shape_k: 1.35 },
    predicted_cpi: 4.45,
    predicted_roas: 2.40,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21150,
    metro_name: 'Houston TX',
    state: 'TX',
    lat: 29.7604,
    lng: -95.3698,
    gamer_population: 2180000,
    population_density_sq_km: 1400,
    trends_index: 88,
    weather_shock_temp_c: 3.8,
    weather_shock_precip_mm: 24.5,
    hill_parameters: { base_roas: 2.75, half_saturation_s: 260, shape_k: 1.42 },
    predicted_cpi: 4.10,
    predicted_roas: 2.68,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21155,
    metro_name: 'Atlanta GA',
    state: 'GA',
    lat: 33.7490,
    lng: -84.3880,
    gamer_population: 1950000,
    population_density_sq_km: 1350,
    trends_index: 89,
    weather_shock_temp_c: 2.2,
    weather_shock_precip_mm: 8.0,
    hill_parameters: { base_roas: 2.80, half_saturation_s: 250, shape_k: 1.48 },
    predicted_cpi: 3.85,
    predicted_roas: 2.95,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21146,
    metro_name: 'Washington DC (Hagrstwn)',
    state: 'DC',
    lat: 38.9072,
    lng: -77.0369,
    gamer_population: 1780000,
    population_density_sq_km: 4300,
    trends_index: 87,
    weather_shock_temp_c: -1.5,
    weather_shock_precip_mm: 14.2,
    hill_parameters: { base_roas: 2.90, half_saturation_s: 265, shape_k: 1.44 },
    predicted_cpi: 5.20,
    predicted_roas: 2.72,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21148,
    metro_name: 'Boston MA-Manchester NH',
    state: 'MA',
    lat: 42.3601,
    lng: -71.0589,
    gamer_population: 1620000,
    population_density_sq_km: 5400,
    trends_index: 85,
    weather_shock_temp_c: -4.0,
    weather_shock_precip_mm: 22.0,
    hill_parameters: { base_roas: 2.65, half_saturation_s: 230, shape_k: 1.39 },
    predicted_cpi: 5.40,
    predicted_roas: 2.55,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21177,
    metro_name: 'San Francisco-Oak-San Jose CA',
    state: 'CA',
    lat: 37.7749,
    lng: -122.4194,
    gamer_population: 2250000,
    population_density_sq_km: 6800,
    trends_index: 96,
    weather_shock_temp_c: 0.5,
    weather_shock_precip_mm: 6.0,
    hill_parameters: { base_roas: 3.35, half_saturation_s: 340, shape_k: 1.62 },
    predicted_cpi: 6.10,
    predicted_roas: 3.20,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21178,
    metro_name: 'Phoenix AZ',
    state: 'AZ',
    lat: 33.4484,
    lng: -112.0740,
    gamer_population: 1540000,
    population_density_sq_km: 1200,
    trends_index: 87,
    weather_shock_temp_c: 5.6,
    weather_shock_precip_mm: 0.0,
    hill_parameters: { base_roas: 2.70, half_saturation_s: 210, shape_k: 1.40 },
    predicted_cpi: 3.75,
    predicted_roas: 2.85,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21179,
    metro_name: 'Seattle-Tacoma WA',
    state: 'WA',
    lat: 47.6062,
    lng: -122.3321,
    gamer_population: 1480000,
    population_density_sq_km: 3400,
    trends_index: 92,
    weather_shock_temp_c: -2.8,
    weather_shock_precip_mm: 45.2,
    hill_parameters: { base_roas: 3.05, half_saturation_s: 235, shape_k: 1.52 },
    predicted_cpi: 5.05,
    predicted_roas: 3.12,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21156,
    metro_name: 'Tampa-St. Pete FL',
    state: 'FL',
    lat: 27.9506,
    lng: -82.4572,
    gamer_population: 1120000,
    population_density_sq_km: 1450,
    trends_index: 80,
    weather_shock_temp_c: 2.9,
    weather_shock_precip_mm: 19.0,
    hill_parameters: { base_roas: 2.45, half_saturation_s: 180, shape_k: 1.34 },
    predicted_cpi: 3.90,
    predicted_roas: 2.48,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21151,
    metro_name: 'Minneapolis-St. Paul MN',
    state: 'MN',
    lat: 44.9778,
    lng: -93.2650,
    gamer_population: 1210000,
    population_density_sq_km: 2800,
    trends_index: 84,
    weather_shock_temp_c: -8.4,
    weather_shock_precip_mm: 28.0,
    hill_parameters: { base_roas: 2.60, half_saturation_s: 195, shape_k: 1.41 },
    predicted_cpi: 4.25,
    predicted_roas: 2.78,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21154,
    metro_name: 'Detroit MI',
    state: 'MI',
    lat: 42.3314,
    lng: -83.0458,
    gamer_population: 1290000,
    population_density_sq_km: 1900,
    trends_index: 78,
    weather_shock_temp_c: -4.5,
    weather_shock_precip_mm: 16.0,
    hill_parameters: { base_roas: 2.35, half_saturation_s: 175, shape_k: 1.30 },
    predicted_cpi: 3.70,
    predicted_roas: 2.38,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21182,
    metro_name: 'Denver CO',
    state: 'CO',
    lat: 39.7392,
    lng: -104.9903,
    gamer_population: 1260000,
    population_density_sq_km: 1800,
    trends_index: 89,
    weather_shock_temp_c: -3.6,
    weather_shock_precip_mm: 14.0,
    hill_parameters: { base_roas: 2.85, half_saturation_s: 205, shape_k: 1.46 },
    predicted_cpi: 4.50,
    predicted_roas: 2.88,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21153,
    metro_name: 'Miami-Ft. Lauderdale FL',
    state: 'FL',
    lat: 25.7617,
    lng: -80.1918,
    gamer_population: 1750000,
    population_density_sq_km: 4600,
    trends_index: 90,
    weather_shock_temp_c: 3.1,
    weather_shock_precip_mm: 35.0,
    hill_parameters: { base_roas: 2.80, half_saturation_s: 245, shape_k: 1.45 },
    predicted_cpi: 4.70,
    predicted_roas: 2.82,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21157,
    metro_name: 'Orlando-Daytona Bch-Melbrn FL',
    state: 'FL',
    lat: 28.5383,
    lng: -81.3792,
    gamer_population: 980000,
    population_density_sq_km: 1100,
    trends_index: 83,
    weather_shock_temp_c: 2.6,
    weather_shock_precip_mm: 22.0,
    hill_parameters: { base_roas: 2.50, half_saturation_s: 160, shape_k: 1.36 },
    predicted_cpi: 3.90,
    predicted_roas: 2.55,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21159,
    metro_name: 'Cleveland-Akron (Canton) OH',
    state: 'OH',
    lat: 41.4993,
    lng: -81.6944,
    gamer_population: 890000,
    population_density_sq_km: 1850,
    trends_index: 76,
    weather_shock_temp_c: -3.8,
    weather_shock_precip_mm: 18.0,
    hill_parameters: { base_roas: 2.25, half_saturation_s: 140, shape_k: 1.28 },
    predicted_cpi: 3.55,
    predicted_roas: 2.30,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21183,
    metro_name: 'Sacramnto-Stkton-Modesto CA',
    state: 'CA',
    lat: 38.5816,
    lng: -121.4944,
    gamer_population: 920000,
    population_density_sq_km: 1750,
    trends_index: 81,
    weather_shock_temp_c: 1.2,
    weather_shock_precip_mm: 4.0,
    hill_parameters: { base_roas: 2.55, half_saturation_s: 155, shape_k: 1.37 },
    predicted_cpi: 4.60,
    predicted_roas: 2.60,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21180,
    metro_name: 'Portland OR',
    state: 'OR',
    lat: 45.5152,
    lng: -122.6784,
    gamer_population: 940000,
    population_density_sq_km: 1950,
    trends_index: 88,
    weather_shock_temp_c: -2.0,
    weather_shock_precip_mm: 38.0,
    hill_parameters: { base_roas: 2.75, half_saturation_s: 170, shape_k: 1.43 },
    predicted_cpi: 4.80,
    predicted_roas: 2.85,
    regional_status: 'CLIMATE_TAILWIND',
  },
  {
    criteria_id: 21161,
    metro_name: 'St. Louis MO',
    state: 'MO',
    lat: 38.6270,
    lng: -90.1994,
    gamer_population: 880000,
    population_density_sq_km: 1900,
    trends_index: 77,
    weather_shock_temp_c: -2.5,
    weather_shock_precip_mm: 15.0,
    hill_parameters: { base_roas: 2.30, half_saturation_s: 145, shape_k: 1.32 },
    predicted_cpi: 3.65,
    predicted_roas: 2.35,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21164,
    metro_name: 'Charlotte NC',
    state: 'NC',
    lat: 35.2271,
    lng: -80.8431,
    gamer_population: 910000,
    population_density_sq_km: 1150,
    trends_index: 84,
    weather_shock_temp_c: 1.8,
    weather_shock_precip_mm: 9.0,
    hill_parameters: { base_roas: 2.65, half_saturation_s: 165, shape_k: 1.40 },
    predicted_cpi: 3.80,
    predicted_roas: 2.75,
    regional_status: 'BOOST_OPPORTUNITY',
  },
  {
    criteria_id: 21158,
    metro_name: 'Pittsburgh PA',
    state: 'PA',
    lat: 40.4406,
    lng: -79.9959,
    gamer_population: 780000,
    population_density_sq_km: 2100,
    trends_index: 75,
    weather_shock_temp_c: -3.0,
    weather_shock_precip_mm: 17.0,
    hill_parameters: { base_roas: 2.20, half_saturation_s: 130, shape_k: 1.29 },
    predicted_cpi: 3.75,
    predicted_roas: 2.25,
    regional_status: 'STABLE_CORE',
  },
  {
    criteria_id: 21166,
    metro_name: 'Raleigh-Durham (Faytvlle) NC',
    state: 'NC',
    lat: 35.7796,
    lng: -78.6382,
    gamer_population: 860000,
    population_density_sq_km: 1250,
    trends_index: 89,
    weather_shock_temp_c: 1.5,
    weather_shock_precip_mm: 11.0,
    hill_parameters: { base_roas: 2.85, half_saturation_s: 160, shape_k: 1.48 },
    predicted_cpi: 3.90,
    predicted_roas: 2.92,
    regional_status: 'BOOST_OPPORTUNITY',
  },
];

export const TOP_25_NIELSEN_DMAS: NielsenDMA[] = [
  { dma_code: 501, google_ads_metro_code: 21149, metro_name: "New York NY", state: "NY", nielsen_rank: 1, lat: 40.7128, lon: -74.0060, population: 20140000, population_weight: 0.1450, gaming_density_index: 1.18, esports_cluster_tag: "EA FC Pro Tier-1 Hub", timezone: "America/New_York", weather_temp_c: 16.8, weather_temp_anom_c: -3.2, weather_precip_mm: 18.5, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 803, google_ads_metro_code: 21175, metro_name: "Los Angeles CA", state: "CA", nielsen_rank: 2, lat: 34.0522, lon: -118.2437, population: 13200000, population_weight: 0.0950, gaming_density_index: 1.25, esports_cluster_tag: "Apex Legends Global Series (ALGS) HQ", timezone: "America/Los_Angeles", weather_temp_c: 21.4, weather_temp_anom_c: 1.4, weather_precip_mm: 0.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 602, google_ads_metro_code: 21160, metro_name: "Chicago IL", state: "IL", nielsen_rank: 3, lat: 41.8781, lon: -87.6298, population: 9610000, population_weight: 0.0692, gaming_density_index: 1.10, esports_cluster_tag: "Battlefield Tactical Ops Midwest", timezone: "America/Chicago", weather_temp_c: 13.2, weather_temp_anom_c: -6.8, weather_precip_mm: 32.1, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 504, google_ads_metro_code: 21147, metro_name: "Philadelphia PA", state: "PA", nielsen_rank: 4, lat: 39.9526, lon: -75.1652, population: 6245000, population_weight: 0.0450, gaming_density_index: 1.05, esports_cluster_tag: "Collegiate eSports Tri-State", timezone: "America/New_York", weather_temp_c: 17.9, weather_temp_anom_c: -2.1, weather_precip_mm: 12.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 623, google_ads_metro_code: 21162, metro_name: "Dallas-Ft. Worth TX", state: "TX", nielsen_rank: 5, lat: 32.7767, lon: -96.7970, population: 7637000, population_weight: 0.0550, gaming_density_index: 1.22, esports_cluster_tag: "Apex & FPS Tournament Capital", timezone: "America/Chicago", weather_temp_c: 24.5, weather_temp_anom_c: 4.5, weather_precip_mm: 5.2, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: true, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 524, google_ads_metro_code: 21155, metro_name: "Atlanta GA", state: "GA", nielsen_rank: 6, lat: 33.7490, lon: -84.3880, population: 6144000, population_weight: 0.0442, gaming_density_index: 1.20, esports_cluster_tag: "EA Sports FC Southeast Invitational", timezone: "America/New_York", weather_temp_c: 22.2, weather_temp_anom_c: 2.2, weather_precip_mm: 8.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 618, google_ads_metro_code: 21150, metro_name: "Houston TX", state: "TX", nielsen_rank: 7, lat: 29.7604, lon: -95.3698, population: 7122000, population_weight: 0.0513, gaming_density_index: 1.19, esports_cluster_tag: "Apex Competitive South", timezone: "America/Chicago", weather_temp_c: 23.8, weather_temp_anom_c: 3.8, weather_precip_mm: 24.5, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 511, google_ads_metro_code: 21146, metro_name: "Washington DC (Hagrstwn)", state: "DC", nielsen_rank: 8, lat: 38.9072, lon: -77.0369, population: 6385000, population_weight: 0.0460, gaming_density_index: 1.12, esports_cluster_tag: "Battlefield Mil-Sim Mid-Atlantic", timezone: "America/New_York", weather_temp_c: 18.5, weather_temp_anom_c: -1.5, weather_precip_mm: 14.2, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 506, google_ads_metro_code: 21148, metro_name: "Boston MA-Manchester NH", state: "MA", nielsen_rank: 9, lat: 42.3601, lon: -71.0589, population: 4940000, population_weight: 0.0356, gaming_density_index: 1.15, esports_cluster_tag: "Collegiate Gaming Northeast", timezone: "America/New_York", weather_temp_c: 16.0, weather_temp_anom_c: -4.0, weather_precip_mm: 22.0, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 807, google_ads_metro_code: 21177, metro_name: "San Francisco-Oak-San Jose CA", state: "CA", nielsen_rank: 10, lat: 37.7749, lon: -122.4194, population: 4750000, population_weight: 0.0342, gaming_density_index: 1.35, esports_cluster_tag: "Respawn & Sims Tech Core", timezone: "America/Los_Angeles", weather_temp_c: 20.5, weather_temp_anom_c: 0.5, weather_precip_mm: 0.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 753, google_ads_metro_code: 21178, metro_name: "Phoenix AZ", state: "AZ", nielsen_rank: 11, lat: 33.4484, lon: -112.0740, population: 4845000, population_weight: 0.0349, gaming_density_index: 1.16, esports_cluster_tag: "Apex Desert Showdown Hub", timezone: "America/Phoenix", weather_temp_c: 32.0, weather_temp_anom_c: 2.0, weather_precip_mm: 0.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 819, google_ads_metro_code: 21179, metro_name: "Seattle-Tacoma WA", state: "WA", nielsen_rank: 12, lat: 47.6062, lon: -122.3321, population: 4018000, population_weight: 0.0289, gaming_density_index: 1.32, esports_cluster_tag: "Pacific Northwest PC Master Hub", timezone: "America/Los_Angeles", weather_temp_c: 14.5, weather_temp_anom_c: -5.5, weather_precip_mm: 28.0, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 539, google_ads_metro_code: 21156, metro_name: "Tampa-St. Pete FL", state: "FL", nielsen_rank: 13, lat: 27.9506, lon: -82.4572, population: 3170000, population_weight: 0.0228, gaming_density_index: 1.08, esports_cluster_tag: "EA Sports FC Sunbelt League", timezone: "America/New_York", weather_temp_c: 26.0, weather_temp_anom_c: 1.0, weather_precip_mm: 15.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 613, google_ads_metro_code: 21151, metro_name: "Minneapolis-St. Paul MN", state: "MN", nielsen_rank: 14, lat: 44.9778, lon: -93.2650, population: 3690000, population_weight: 0.0266, gaming_density_index: 1.12, esports_cluster_tag: "Northern Winter Indoor Hub", timezone: "America/Chicago", weather_temp_c: 11.5, weather_temp_anom_c: -8.5, weather_precip_mm: 26.4, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 505, google_ads_metro_code: 21154, metro_name: "Detroit MI", state: "MI", nielsen_rank: 15, lat: 42.3314, lon: -83.0458, population: 4392000, population_weight: 0.0316, gaming_density_index: 0.98, esports_cluster_tag: "Great Lakes Tactical Gaming", timezone: "America/Detroit", weather_temp_c: 13.8, weather_temp_anom_c: -6.2, weather_precip_mm: 20.1, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 751, google_ads_metro_code: 21182, metro_name: "Denver CO", state: "CO", nielsen_rank: 16, lat: 39.7392, lon: -104.9903, population: 2963000, population_weight: 0.0213, gaming_density_index: 1.24, esports_cluster_tag: "Mountain West Apex Regional", timezone: "America/Denver", weather_temp_c: 12.0, weather_temp_anom_c: -8.0, weather_precip_mm: 19.5, t3_lead_shock: true, t5_lead_shock: true, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.32, recommended_pacing_action: "20% Surge Pacing Boost" },
  { dma_code: 534, google_ads_metro_code: 21157, metro_name: "Orlando-Daytona Bch-Melbrn FL", state: "FL", nielsen_rank: 17, lat: 28.5383, lon: -81.3792, population: 2673000, population_weight: 0.0192, gaming_density_index: 1.17, esports_cluster_tag: "EA Tiburon Studio Community Hub", timezone: "America/New_York", weather_temp_c: 25.5, weather_temp_anom_c: 0.5, weather_precip_mm: 10.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 528, google_ads_metro_code: 21153, metro_name: "Miami-Ft. Lauderdale FL", state: "FL", nielsen_rank: 18, lat: 25.7617, lon: -80.1918, population: 6138000, population_weight: 0.0442, gaming_density_index: 1.14, esports_cluster_tag: "EA FC LATAM Gateway", timezone: "America/New_York", weather_temp_c: 27.0, weather_temp_anom_c: 1.0, weather_precip_mm: 16.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 510, google_ads_metro_code: 21159, metro_name: "Cleveland-Akron (Canton) OH", state: "OH", nielsen_rank: 19, lat: 41.4993, lon: -81.6944, population: 2088000, population_weight: 0.0150, gaming_density_index: 0.95, esports_cluster_tag: "Rust Belt Esports League", timezone: "America/New_York", weather_temp_c: 16.5, weather_temp_anom_c: -3.5, weather_precip_mm: 14.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: true, t15_lead_shock: true, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 862, google_ads_metro_code: 21183, metro_name: "Sacramnto-Stkton-Modesto CA", state: "CA", nielsen_rank: 20, lat: 38.5816, lon: -121.4944, population: 2397000, population_weight: 0.0173, gaming_density_index: 1.11, esports_cluster_tag: "NorCal Live Streamer Cluster", timezone: "America/Los_Angeles", weather_temp_c: 22.0, weather_temp_anom_c: 2.0, weather_precip_mm: 0.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 820, google_ads_metro_code: 21180, metro_name: "Portland OR", state: "OR", nielsen_rank: 21, lat: 45.5152, lon: -122.6784, population: 2510000, population_weight: 0.0181, gaming_density_index: 1.25, esports_cluster_tag: "Indie & Sims Creator Community", timezone: "America/Los_Angeles", weather_temp_c: 18.0, weather_temp_anom_c: -2.0, weather_precip_mm: 8.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 609, google_ads_metro_code: 21161, metro_name: "St. Louis MO", state: "MO", nielsen_rank: 22, lat: 38.6270, lon: -90.1994, population: 2820000, population_weight: 0.0203, gaming_density_index: 1.01, esports_cluster_tag: "Midwest Gateway Esports", timezone: "America/Chicago", weather_temp_c: 21.0, weather_temp_anom_c: 1.0, weather_precip_mm: 4.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 517, google_ads_metro_code: 21164, metro_name: "Charlotte NC", state: "NC", nielsen_rank: 23, lat: 35.2271, lon: -80.8431, population: 2660000, population_weight: 0.0192, gaming_density_index: 1.09, esports_cluster_tag: "Carolinas Competitive Gaming", timezone: "America/New_York", weather_temp_c: 21.5, weather_temp_anom_c: 1.5, weather_precip_mm: 6.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 508, google_ads_metro_code: 21158, metro_name: "Pittsburgh PA", state: "PA", nielsen_rank: 24, lat: 40.4406, lon: -79.9959, population: 2420000, population_weight: 0.0174, gaming_density_index: 0.96, esports_cluster_tag: "Appalachian Collegiate Arena", timezone: "America/New_York", weather_temp_c: 17.0, weather_temp_anom_c: -3.0, weather_precip_mm: 11.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" },
  { dma_code: 560, google_ads_metro_code: 21166, metro_name: "Raleigh-Durham (Faytvlle) NC", state: "NC", nielsen_rank: 25, lat: 35.7796, lon: -78.6382, population: 2110000, population_weight: 0.0152, gaming_density_index: 1.21, esports_cluster_tag: "Research Triangle Dev & Gaming", timezone: "America/New_York", weather_temp_c: 22.0, weather_temp_anom_c: 2.0, weather_precip_mm: 5.0, t3_lead_shock: false, t5_lead_shock: false, t8_lead_shock: false, t15_lead_shock: false, indoor_elasticity_multiplier: 1.05, recommended_pacing_action: "Baseline Pacing" }
];

export const WEATHER_TRAJECTORY_DATA: WeatherTrajectoryPoint[] = Array.from({ length: 90 }, (_, i) => {
  const day = i + 1;
  const isOctPeak = day >= 20 && day <= 35;
  const isNovDip = day >= 50 && day <= 65;
  
  // Synthesize realistic WeatherNext 2.0 lead trajectory
  let tempAnom = Number((Math.sin(day / 7) * 4.5 - (isOctPeak ? 5.5 : 0) + (isNovDip ? -7.2 : 0)).toFixed(1));
  let precip = Number((Math.max(0, Math.cos(day / 5) * 20 + (isOctPeak ? 22 : 4))).toFixed(1));
  
  // Shock multipliers across horizons
  let t3 = Number((1.0 + Math.max(0, -tempAnom / 18.0) * 0.45 + (precip > 15 ? 0.18 : 0.02)).toFixed(2));
  t3 = Math.min(1.50, Math.max(1.00, t3));
  
  let t5 = Number((t3 * 0.96 + Math.sin(day / 3) * 0.03).toFixed(2));
  let t8 = Number((t3 * 0.92 + Math.cos(day / 4) * 0.04).toFixed(2));
  let t15 = Number((t3 * 0.88 + 0.05).toFixed(2));

  return {
    day_offset: day,
    date_label: `D-${90 - day}`,
    temp_anomaly_c: tempAnom,
    precip_mm: precip,
    t3_elasticity: t3,
    t5_elasticity: t5,
    t8_elasticity: t8,
    t15_elasticity: t15,
    realized_elasticity: t3,
    surge_threshold: 1.15,
  };
});

