import {
  CreativeAsset,
  AttributionModelSummary,
  BAREPersonaEvaluation,
  GamerPersonaProfile,
  ScenarioSimulationResult,
  TelemetryLog,
  ConflictFatigueData,
  ShapleyPreTestAuditData,
} from '@/types';

export const MOCK_CREATIVE_ASSETS: CreativeAsset[] = [
  {
    asset_id: 'asset-nba2k26-launch-trailer',
    campaign_id: 'camp-nba2k26-launch',
    franchise: 'NBA 2K26',
    title: 'NBA 2K26: The City & ProPLAY Gameplay Reveal Trailer',
    video_url: '/mock_videos/nba2k26_gameplay_reveal.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=60',
    duration_sec: 45,
    media_type: 'VIDEO',
    funnel_stage: 'ToFu_Exploration',
    detected_mechanics: [
      {
        mechanic_id: 'mech-2k-01',
        mechanic_name: 'ProPLAY Volumetric Step-Back Green Release',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.97,
        timestamp_start_sec: 2,
        timestamp_end_sec: 12,
        bounding_box: { x: 20, y: 15, width: 60, height: 65 },
        description: 'Broadcast-quality 1-to-1 capture of signature step-back into green-release buzzer beater.',
        visual_hook: 'Green flash release meter with courtside particle glow',
        audio_cue: 'Net swish sound FX & roaring Madison Square Garden crowd',
      },
      {
        mechanic_id: 'mech-2k-02',
        mechanic_name: 'The City Neon Rooftops & Streetball Parks',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.95,
        timestamp_start_sec: 13,
        timestamp_end_sec: 24,
        bounding_box: { x: 10, y: 15, width: 80, height: 70 },
        description: 'Sweeping city panorama featuring 3v3 streetball courts, hoverboard transit, and live Nike/Jordan apparel drops.',
        visual_hook: 'Neon skyline hoverboard ride and park squad walkup',
        audio_cue: 'Heavy 808 hip-hop bass drop & announcer hype call',
      },
      {
        mechanic_id: 'mech-2k-03',
        mechanic_name: 'MyCAREER Cap Breaker 99 OVR Milestone',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.92,
        timestamp_start_sec: 25,
        timestamp_end_sec: 35,
        bounding_box: { x: 28, y: 22, width: 45, height: 55 },
        description: 'MyPLAYER build attribute unlocking 99 OVR Cap Breaker and Tier-1 Hall of Fame Posterizer badge.',
        visual_hook: 'Badge tier transformation burst and OVR counter ticking to 99',
        audio_cue: 'Level-up brass chord fanfare',
      },
      {
        mechanic_id: 'mech-2k-04',
        mechanic_name: 'MyTEAM 100 OVR Holo Dark Matter Kobe Pack Opening',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.94,
        timestamp_start_sec: 36,
        timestamp_end_sec: 45,
        bounding_box: { x: 22, y: 18, width: 55, height: 65 },
        description: 'Holographic pack tear sequence revealing 100 OVR Dark Matter Kobe Bryant with instant Hall of Fame Edition CTA.',
        visual_hook: 'Holographic purple-to-gold flame card burst',
        audio_cue: 'Card slice sound effect into explosive arena horn',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 96, recommendation: 'Optimal hero launch unit; highest conversion on ProPLAY green release hook.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 94, recommendation: 'Twitch/YouTube stream drops align with Dark Matter pack code CTA.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 92, recommendation: 'Trim first 12s to focus immediately on VC bundle and ProPASS track.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 82, recommendation: 'Resize to 9:16 vertical and add subtitles for MyNBA Companion app.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 88, recommendation: 'High-contrast courtside ribbon loop for NBA arena digital boards.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 72, recommendation: 'Static keyframe of 100 OVR Holo card fits timeout overlays.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.50, MoFu: 0.25, BoFu: 0.25 },
        dominant_color_palette: ['#E51B24', '#0E1A29', '#FFD200', '#FFFFFF'],
        audio_tempo_bpm: 135,
        dialogue_word_count: 38,
        action_density_score: 0.94,
        brand_logo_exposure_sec: 5.2,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-10T14:00:00Z',
  },
  {
    asset_id: 'asset-borderlands4-reveal',
    campaign_id: 'camp-borderlands4-reveal',
    franchise: 'Borderlands 4',
    title: 'Borderlands 4: Mayhem 10 Co-Op Vault Hunter Trailer',
    video_url: '/mock_videos/borderlands4_mayhem_trailer.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=800&auto=format&fit=crop&q=60',
    duration_sec: 40,
    media_type: 'VIDEO',
    funnel_stage: 'ToFu_Exploration',
    detected_mechanics: [
      {
        mechanic_id: 'mech-bl4-01',
        mechanic_name: '4-Player Co-Op Elemental Mayhem Skirmish',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.96,
        timestamp_start_sec: 1,
        timestamp_end_sec: 14,
        bounding_box: { x: 15, y: 15, width: 70, height: 65 },
        description: 'High-octane cel-shaded gunplay featuring corrosive rockets, electric snipers, and Siren phase-lock.',
        visual_hook: 'Explosive multi-colored elemental explosions and damage numbers',
        audio_cue: 'Industrial rock guitar riff and Siren voice line',
      },
      {
        mechanic_id: 'mech-bl4-02',
        mechanic_name: 'Legendary Orange Loot Shower & Gun Inspection',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.94,
        timestamp_start_sec: 15,
        timestamp_end_sec: 28,
        bounding_box: { x: 22, y: 20, width: 56, height: 60 },
        description: 'Raid boss loot beam explosion displaying 6 unique Legendary weapons with walking gun animation.',
        visual_hook: 'Golden beacon beams reaching into the sky with weapon stats UI',
        audio_cue: 'Legendary loot chime & Claptrap witty quip',
      },
      {
        mechanic_id: 'mech-bl4-03',
        mechanic_name: 'Deluxe Season Pass Pre-Order Discount Voucher',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.91,
        timestamp_start_sec: 29,
        timestamp_end_sec: 40,
        bounding_box: { x: 25, y: 20, width: 50, height: 55 },
        description: 'Deluxe Season Pass bundle displaying 4 future campaign story expansions + Butt Stallion weapon skin.',
        visual_hook: 'Butt Stallion diamond sparkle and pre-order badge',
        audio_cue: 'Loud guitar solo finale with pre-order narrator CTA',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 95, recommendation: 'High conversion on co-op shooter fans.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 93, recommendation: 'Exceptional for Twitch Mayhem raid stream overlays.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 88, recommendation: 'Highlights cosmetic head packs and season pass.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 75, recommendation: 'Add closed captions for muted video feeds.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 80, recommendation: 'Great for shooter cross-promotion.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 40, recommendation: 'Lacks sports context for arena boards.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.45, MoFu: 0.35, BoFu: 0.20 },
        dominant_color_palette: ['#FF7A00', '#FFE600', '#1F2430', '#00F0FF'],
        audio_tempo_bpm: 148,
        action_density_score: 0.95,
        brand_logo_exposure_sec: 4.5,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-11T16:20:00Z',
  },
  {
    asset_id: 'asset-civ7-era-trailer',
    campaign_id: 'camp-civ7-reveal',
    franchise: 'Civilization VII',
    title: 'Sid Meier\'s Civilization VII: Ages of Humankind Strategy Trailer',
    video_url: '/mock_videos/civ7_ages_trailer.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=60',
    duration_sec: 35,
    media_type: 'VIDEO',
    funnel_stage: 'MoFu_Progression',
    detected_mechanics: [
      {
        mechanic_id: 'mech-civ7-01',
        mechanic_name: 'Antiquity to Exploration Era Transition Cinematic',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.98,
        timestamp_start_sec: 1,
        timestamp_end_sec: 15,
        bounding_box: { x: 12, y: 15, width: 76, height: 68 },
        description: 'Visual time-lapse showing Roman marble colosseums transforming into Renaissance galleons and naval empires.',
        visual_hook: 'Seamless fog-of-war reveal and wonder construction time-lapse',
        audio_cue: 'Epic orchestral symphony by Christopher Tin',
      },
      {
        mechanic_id: 'mech-civ7-02',
        mechanic_name: 'Tactical Army Commander & Diplomatic League Mechanics',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.94,
        timestamp_start_sec: 16,
        timestamp_end_sec: 26,
        bounding_box: { x: 20, y: 20, width: 60, height: 60 },
        description: 'Zoomed-in tactical view of army commander formations, siege ballistas, and UN diplomatic votes.',
        visual_hook: 'Hexagonal grid tactical animations and diplomatic seal stamps',
        audio_cue: 'Battle drums and voiceover quotation by Gwendoline Christie',
      },
      {
        mechanic_id: 'mech-civ7-03',
        mechanic_name: 'Founders Edition 5-Day Early Access Pre-Order',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.92,
        timestamp_start_sec: 27,
        timestamp_end_sec: 35,
        bounding_box: { x: 25, y: 20, width: 50, height: 55 },
        description: 'Founders Edition packaging with 5-day early access + Ages of Humankind Season Pass voucher.',
        visual_hook: 'Golden Civ logo and leader bust showcase',
        audio_cue: 'Triumphant brass fanfare',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 97, recommendation: 'Top performing strategy title placement with high direct pre-order rate.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 86, recommendation: 'Great for turn notification companion app.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 90, recommendation: 'Leader pack DLC catalog drives immediate expansion pre-orders.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 88, recommendation: 'Fits long-form Twitch strategy gameplay streams.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 74, recommendation: 'Effective during multiplayer turn loading screens.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 25, recommendation: 'Complex historical visuals mismatched for sports arena boards.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.40, MoFu: 0.35, BoFu: 0.25 },
        dominant_color_palette: ['#38BDF8', '#FFB703', '#1E293B', '#FFFFFF'],
        audio_tempo_bpm: 105,
        action_density_score: 0.72,
        brand_logo_exposure_sec: 5.0,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-12T10:30:00Z',
  },
];

export const MOCK_ATTRIBUTION_SUMMARY: AttributionModelSummary = {
  model_id: 'attr-model-2k-2026-q3',
  franchise: 'NBA 2K26',
  updated_at: '2026-08-15T12:00:00Z',
  features: [
    {
      feature_id: 'feat-01',
      feature_name: 'ProPLAY Step-Back Green Release',
      franchise: 'NBA 2K26',
      funnel_stage: 'ToFu_Exploration',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 26,
      roas_impact_y: 3.45,
      quadrant: 'GOLD_MINES',
      confidence: 0.97,
      sample_size: 520000,
      action_recommendation: 'Scale spend by +40% in top 15 NBA DMAs. Exceptional conversion with zero audience fatigue.',
      description: 'Authentic 1-to-1 motion capture generates instant viewer retention and high early-funnel click-through.',
    },
    {
      feature_id: 'feat-02',
      feature_name: 'The City Neon Streetball Parks',
      franchise: 'NBA 2K26',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STREAMING_OVERLAYS',
      frequency_x: 55,
      roas_impact_y: 2.85,
      quadrant: 'CORE_DRIVERS',
      confidence: 0.95,
      sample_size: 980000,
      action_recommendation: 'Maintain continuous flighting; anchors core casual and returning player acquisition.',
      description: 'Vibrant streetball lifestyle and park fashion consistently convert lapsed players.',
    },
    {
      feature_id: 'feat-03',
      feature_name: 'MyTEAM 100 OVR Holo Dark Matter Pack',
      franchise: 'NBA 2K26',
      funnel_stage: 'BoFu_Conversion',
      surface: 'IN_GAME_STORE',
      frequency_x: 82,
      roas_impact_y: 3.10,
      quadrant: 'CORE_DRIVERS',
      confidence: 0.96,
      sample_size: 1650000,
      action_recommendation: 'Pair with weekend promo drops; high day-7 monetization return on VIP whales.',
      description: 'Premium holographic pack opening animations deliver peak purchase conversion.',
    },
    {
      feature_id: 'feat-04',
      feature_name: 'Cap Breaker 99 OVR Progression Hook',
      franchise: 'NBA 2K26',
      funnel_stage: 'MoFu_Progression',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 48,
      roas_impact_y: 2.25,
      quadrant: 'WORKHORSES',
      confidence: 0.93,
      sample_size: 820000,
      action_recommendation: 'Optimize audio callouts and pacing to push feature into Gold Mines zone.',
      description: 'Dependable conversion among dedicated The REC and Pro-Am players seeking badge milestone mastery.',
    },
    {
      feature_id: 'feat-05',
      feature_name: 'Borderlands 4 Mayhem Raid Boss Skirmish',
      franchise: 'Borderlands 4',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STREAMING_OVERLAYS',
      frequency_x: 20,
      roas_impact_y: 2.65,
      quadrant: 'GOLD_MINES',
      confidence: 0.94,
      sample_size: 340000,
      action_recommendation: 'Expand A/B test budget by $75k across YouTube Shorts and Twitch takeovers.',
      description: 'Viral 4-player co-op combat highlights trigger strong pre-order intent among shooter audiences.',
    },
    {
      feature_id: 'feat-06',
      feature_name: 'Civilization VII Era Transition Showcase',
      franchise: 'Civilization VII',
      funnel_stage: 'MoFu_Progression',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 42,
      roas_impact_y: 2.15,
      quadrant: 'WORKHORSES',
      confidence: 0.95,
      sample_size: 610000,
      action_recommendation: 'Target PC strategy hubs and grand strategy audiences.',
      description: 'High resonance with 4X strategy purists who value deep historical era transitions.',
    },
    {
      feature_id: 'feat-07',
      feature_name: 'Aggressive Unskippable Pop-Up Ads',
      franchise: 'NBA 2K26',
      funnel_stage: 'BoFu_Conversion',
      surface: 'IN_GAME_STORE',
      frequency_x: 88,
      roas_impact_y: -1.65,
      quadrant: 'MONEY_PITS',
      confidence: 0.98,
      sample_size: 1450000,
      action_recommendation: 'Kill immediately. Generates severe friction and increases player tilt churn by 5.4%.',
      description: 'Forced unskippable ads during game load screens provoke community backlash and uninstall risk.',
    },
  ],
  gemini_cot_reasoning: {
    thinking_level: 'HIGH',
    model: 'gemini-3.6-flash',
    executive_summary: 'Shapley attribution analysis confirms that ProPLAY 1-to-1 motion capture and 100 OVR Holo Dark Matter pack reveals deliver the strongest incremental lift for NBA 2K26 across top 15 DMAs.',
    key_drivers: [
      'ProPLAY Step-Back Green Release delivers +44.5% thumb-stop CTR lift in the initial 3 seconds.',
      'Guaranteed 100 OVR Holo Dark Matter pack toppers drive 3.45x marginal ROAS during Friday promo windows.',
      'Cap Breaker 99 OVR milestone messaging anchors core retention among The REC and Pro-Am squads.'
    ],
    risk_factors: [
      'Aggressive unskippable in-game popups depress ROAS by -1.65x and elevate churn risk.',
      'Repetitive static store banners suffer 22% fatigue decay within 72 hours of flight.'
    ],
    strategic_action_plan: [
      {
        action: 'Reallocate 35% of programmatic spend into ProPLAY 9:16 vertical video units.',
        expected_lift: '+28% D7 Conversion Rate',
        rationale: 'High thumb-stop power converts casual basketball fans into pre-orders.'
      },
      {
        action: 'Deploy situationally triggered loss-mitigation shields for The REC players on 3-game defeat streaks.',
        expected_lift: '+24% Session Retention',
        rationale: 'Neutralizes tilt churn and protects seasonal rep progression.'
      }
    ],
    thinking_trace: [
      '1. Ingested 5.2M impressions across YouTube, TikTok, Steam, and 2K in-game placements.',
      '2. Computed Shapley feature value decomposition isolating ProPLAY vs Dark Matter pack reveal effects.',
      '3. Fitted hierarchical Bayesian MMM curves across 25 Nielsen DMAs with basketball franchise density.',
      '4. Validated multi-agent BARE persona simulation convergence at 95% confidence.'
    ]
  }
};

export const MOCK_GAMER_PROFILES: GamerPersonaProfile[] = [
  {
    persona_id: 'persona-grinder',
    archetype: 'MYCAREER_HOOPER',
    name: 'Marcus "Buckets" Hayes',
    age_range: '19-24',
    income_tier: '$35k - $55k',
    preferred_franchise: 'NBA 2K26',
    gaming_hours_weekly: 36,
    price_sensitivity_score: 45,
    competitive_drive: 98,
    lore_immersion: 30,
    social_connection: 85,
    monetization_affinity: 65,
    avatar_url: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&auto=format&fit=crop&q=60',
    description: 'High-skill The City 99 OVR Point Guard focused strictly on green release timing, ProPLAY animations, The REC win streaks, and Cap Breakers.',
  },
  {
    persona_id: 'persona-whale',
    archetype: 'MYTEAM_WHALE',
    name: 'Kaito "Collector" Tanaka',
    age_range: '28-38',
    income_tier: '$150k - $240k',
    preferred_franchise: 'NBA 2K26',
    gaming_hours_weekly: 24,
    price_sensitivity_score: 15,
    competitive_drive: 90,
    lore_immersion: 20,
    social_connection: 80,
    monetization_affinity: 98,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=60',
    description: 'High-disposable-income collector dedicated to assembling 100 OVR Holo Dark Matter squads and dominating the Unlimited auction leaderboard.',
  },
  {
    persona_id: 'persona-lore',
    archetype: '4X_GRAND_STRATEGIST',
    name: 'Alexandre Silva',
    age_range: '26-34',
    income_tier: '$70k - $95k',
    preferred_franchise: 'Civilization VII',
    gaming_hours_weekly: 18,
    price_sensitivity_score: 50,
    competitive_drive: 45,
    lore_immersion: 96,
    social_connection: 55,
    monetization_affinity: 50,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=60',
    description: 'Deep historical grand strategy enthusiast playing on Diety difficulty, invested in Ages of Antiquity leader packs and civilization balance.',
  },
  {
    persona_id: 'persona-socializer',
    archetype: 'VAULT_HUNTER_SQUAD',
    name: 'Chloe "Siren" Bennett',
    age_range: '21-28',
    income_tier: '$45k - $68k',
    preferred_franchise: 'Borderlands 4',
    gaming_hours_weekly: 22,
    price_sensitivity_score: 60,
    competitive_drive: 65,
    lore_immersion: 75,
    social_connection: 95,
    monetization_affinity: 40,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=60',
    description: 'Dedicated 4-player co-op raider playing Mayhem 10 with friends on Discord, passionate about legendary loot hunts and character cosmetic skins.',
  },
];

export const MOCK_BARE_EVALUATIONS: Record<string, BAREPersonaEvaluation> = {
  'persona-grinder': {
    persona_id: 'persona-grinder',
    archetype: 'MYCAREER_HOOPER',
    base_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: 'The ProPLAY step-back looks clean, but I hope the green window is consistent online without input delay in The REC.',
      detected_objections: ['Server latency concerns in The REC', 'Unskippable City transit'],
      sentiment_score: 0.92,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.94,
        willingness_to_pay_usd: 99.99,
        churn_risk_probability: 0.08,
        conversion_probability: 0.88,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 98,
        visual_fidelity: 96,
        pricing_fairness: 82,
        fomo_intensity: 90,
        community_trust: 88,
      },
      friction_mitigation_notes: 'Highlight 128-tick online server architecture and instant fast-travel menu teleportation.',
    },
  },
  'persona-whale': {
    persona_id: 'persona-whale',
    archetype: 'MYTEAM_WHALE',
    base_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: '100 OVR Holo Kobe topper is fire! As long as pack odds are clearly posted and auction house sniping is protected against bots, I will buy the Hall of Fame Edition immediately.',
      detected_objections: ['Auction house bot snipers', 'Pack odds transparency'],
      sentiment_score: 0.96,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.98,
        willingness_to_pay_usd: 149.99,
        churn_risk_probability: 0.04,
        conversion_probability: 0.95,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 94,
        visual_fidelity: 98,
        pricing_fairness: 88,
        fomo_intensity: 98,
        community_trust: 92,
      },
      friction_mitigation_notes: 'Emphasize verified pack odds disclosures and guaranteed box topper security.',
    },
  },
  'persona-lore': {
    persona_id: 'persona-lore',
    archetype: '4X_GRAND_STRATEGIST',
    base_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: 'Civilization VII Antiquity era transitions look extraordinary. I want to make sure leader bonuses and military commander formations maintain historical authenticity.',
      detected_objections: ['Microtransactions in strategy titles'],
      sentiment_score: 0.88,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.90,
        willingness_to_pay_usd: 129.99,
        churn_risk_probability: 0.12,
        conversion_probability: 0.82,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 90,
        visual_fidelity: 94,
        pricing_fairness: 86,
        fomo_intensity: 75,
        community_trust: 94,
      },
      friction_mitigation_notes: 'Promote comprehensive Ages of Humankind Season Pass and historical developer deep dives.',
    },
  },
  'persona-socializer': {
    persona_id: 'persona-socializer',
    archetype: 'VAULT_HUNTER_SQUAD',
    base_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: 'Borderlands 4 4-player co-op with cross-play is an instant buy for our Discord squad. Excited for Mayhem 10 raid bosses!',
      detected_objections: ['Cross-play voice chat stability'],
      sentiment_score: 0.93,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.92,
        willingness_to_pay_usd: 69.99,
        churn_risk_probability: 0.10,
        conversion_probability: 0.85,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 96,
        visual_fidelity: 92,
        pricing_fairness: 90,
        fomo_intensity: 85,
        community_trust: 90,
      },
      friction_mitigation_notes: 'Highlight seamless cross-platform Discord lobby integrations.',
    },
  },
};

export const MOCK_CONFLICT_FATIGUE_OCT24_27: ConflictFatigueData = {
  target_campaign_id: 'camp-nba2k26-hof-launch',
  target_campaign_name: 'NBA 2K26 Hall of Fame Launch Flight',
  conflicting_campaign_id: 'camp-nba2k26-vc-vault-promo',
  conflicting_campaign_name: 'NBA 2K26 Black Friday 450k VC Vault',
  target_franchise: 'NBA 2K26',
  conflicting_franchise: 'NBA 2K26',
  flight_start: '2026-10-24',
  flight_end: '2026-10-27',
  shared_ea_id_overlap_pct: 32.5,
  shared_player_count: 145000,
  ad_fatigue_suppression_penalty_pct: 12.4,
  net_bookings_risk_usd: 185000,
  recommended_timeline_shift_days: 4,
  mitigated_flight_start: '2026-10-28',
  mitigated_flight_end: '2026-10-31',
  projected_net_bookings_recovery_usd: 165000,
  baseline_net_bookings_usd: 1450000,
  unmitigated_net_bookings_usd: 1265000,
  post_mitigation_net_bookings_usd: 1430000,
  projected_installs: 85000,
  blended_cpi_usd: 4.85,
  day7_roas: 3.45,
  mitigation_strategy: 'Stagger VC promo flight 4 days post-launch to prevent creative fatigue among The City grinders.',
  status: 'AMBER_COLLISION_DETECTED',
};

export const MOCK_BELLINGHAM_SHAPLEY_AUDIT: ShapleyPreTestAuditData = {
  franchise: 'NBA 2K26',
  asset_title: 'NBA 2K26 - Official Gameplay Reveal Trailer (15s Pre-Test)',
  comparison_pair: 'ProPLAY Step-Back Green Release vs 100 OVR Holo Dark Matter Walkout',
  funnel_balance_index: 0.78,
  top_of_funnel_score: 44.5,
  lower_funnel_score: 34.2,
  predicted_d7_roas: 3.65,
  audit_verdict: 'BALANCED_HIGH_POTENTIAL',
  prescriptive_action: 'Deploy ProPLAY Step-Back hook in 0:00-0:03 for viral thumb-stop (+44.5% CTR), bridge The City park gameplay at 0:03-0:08, and transition to 100 OVR Holo Dark Matter Walkout at 0:08-0:15 for high CTI monetization (+34.2% CTI / 3.65x ROAS).',
  recommended_edit: 'Sequence 9:16 vertical cut with ProPLAY step-back intro into Kobe 100 OVR Holo walkout climax.',
  features: [
    {
      feature_name: '100 OVR Holo Dark Matter Walkout',
      category: 'LOWER_FUNNEL_MONETIZATION',
      funnel_tier: 'BOFU',
      marginal_ctr_lift_pct: 5.4,
      marginal_cti_lift_pct: 34.2,
      marginal_d7_roas_multiplier: 3.65,
      confidence_score: 0.97,
      description: 'High intent, high-converting walkout animation hook driving direct in-game VC vault and promo box purchases.',
      timestamp_start_sec: 7,
      timestamp_end_sec: 12,
    },
    {
      feature_name: 'ProPLAY Step-Back Green Release',
      category: 'TOP_OF_FUNNEL',
      funnel_tier: 'TOFU',
      marginal_ctr_lift_pct: 44.5,
      marginal_cti_lift_pct: -8.5,
      marginal_d7_roas_multiplier: 2.10,
      confidence_score: 0.95,
      description: 'Viral stopping power and high click-through rate, capturing immediate TikTok and Instagram Reels attention.',
      timestamp_start_sec: 0,
      timestamp_end_sec: 3,
    },
  ],
  storybeats: [
    {
      id: '2k-b1',
      timeframe: '0:00 - 0:03',
      startSec: 0,
      endSec: 3,
      title: 'ProPLAY Step-Back Green Release',
      category: 'TOP_OF_FUNNEL',
      tier: 'TOFU',
      ctrLift: 44.5,
      ctiLift: -8.5,
      roas: 2.10,
      description: 'Viral stopping power and high click-through rate thumb-stop hook capturing immediate basketball community attention.',
    },
    {
      id: '2k-b2',
      timeframe: '0:03 - 0:07',
      startSec: 3,
      endSec: 7,
      title: 'The City Park 3v3 Rooftop Skirmish',
      category: 'NEUTRAL_ENGAGEMENT',
      tier: 'MOFU',
      ctrLift: 16.8,
      ctiLift: 6.2,
      roas: 2.45,
      description: 'Streetball culture bridge connecting individual kinetic skill into vibrant social park gameplay.',
    },
    {
      id: '2k-b3',
      timeframe: '0:07 - 0:12',
      startSec: 7,
      endSec: 12,
      title: 'MyTEAM 100 OVR Holo Kobe Bryant Walkout',
      category: 'LOWER_FUNNEL_MONETIZATION',
      tier: 'BOFU',
      ctrLift: 5.4,
      ctiLift: 34.2,
      roas: 3.65,
      description: 'High intent, high-converting holographic walkout animation driving direct VC bundle conversions.',
    },
    {
      id: '2k-b4',
      timeframe: '0:12 - 0:15',
      startSec: 12,
      endSec: 15,
      title: 'Hall of Fame Edition Early Access CTA',
      category: 'BOFU',
      tier: 'BOFU',
      ctrLift: 6.2,
      ctiLift: 21.0,
      roas: 3.30,
      description: 'Direct response closing unit converting accumulated intent with 100,000 VC + 12-Month NBA League Pass incentive.',
    },
  ],
};

export const MOCK_APEX_SHAPLEY_AUDIT: ShapleyPreTestAuditData = {
  franchise: 'Borderlands 4',
  asset_title: 'Borderlands 4 Mayhem 10 - Reveal Trailer (15s Pre-Test)',
  comparison_pair: 'Mayhem 10 Legendary Loot Shower vs Siren Phase-Lock Action Hook',
  funnel_balance_index: 0.76,
  top_of_funnel_score: 40.2,
  lower_funnel_score: 29.8,
  predicted_d7_roas: 3.25,
  audit_verdict: 'BALANCED_HIGH_POTENTIAL',
  prescriptive_action: 'Open with Siren Phase-Lock action hook in first 3 seconds (0:00-0:03) for viral thumb-stop (+40.2% CTR), bridge 4-player team coordination at 0:03-0:08, and close with Legendary Loot Shower and Deluxe Season Pass CTA at 0:08-0:15 (+29.8% CTI / 3.25x ROAS).',
  recommended_edit: 'Combine explosive elemental combat hook with golden legendary weapon payoff.',
  features: [
    {
      feature_name: 'Mayhem 10 Legendary Loot Shower',
      category: 'LOWER_FUNNEL_MONETIZATION',
      funnel_tier: 'BOFU',
      marginal_ctr_lift_pct: 7.2,
      marginal_cti_lift_pct: 29.8,
      marginal_d7_roas_multiplier: 3.25,
      confidence_score: 0.95,
      description: 'Premium loot drop showcase driving high-tier deluxe edition pre-orders and immediate monetization.',
      timestamp_start_sec: 7,
      timestamp_end_sec: 12,
    },
    {
      feature_name: 'Siren Phase-Lock Action Hook',
      category: 'TOP_OF_FUNNEL',
      funnel_tier: 'TOFU',
      marginal_ctr_lift_pct: 40.2,
      marginal_cti_lift_pct: -7.5,
      marginal_d7_roas_multiplier: 2.05,
      confidence_score: 0.93,
      description: 'High-velocity action mechanics capturing immediate gamer attention and driving top-of-funnel CTR.',
      timestamp_start_sec: 0,
      timestamp_end_sec: 3,
    },
  ],
  storybeats: [
    {
      id: 'bl4-b1',
      timeframe: '0:00 - 0:03',
      startSec: 0,
      endSec: 3,
      title: 'Siren Phase-Lock Action Hook',
      category: 'TOP_OF_FUNNEL',
      tier: 'TOFU',
      ctrLift: 40.2,
      ctiLift: -7.5,
      roas: 2.05,
      description: 'High-velocity cel-shaded combat capturing immediate gamer attention and driving top-of-funnel CTR.',
    },
    {
      id: 'bl4-b2',
      timeframe: '0:03 - 0:07',
      startSec: 3,
      endSec: 7,
      title: '4-Player Co-Op Tactical Boss Assault',
      category: 'NEUTRAL_ENGAGEMENT',
      tier: 'MOFU',
      ctrLift: 14.5,
      ctiLift: 7.8,
      roas: 2.50,
      description: 'Squad communication showcase bridging kinetic movement into cooperative strategy and team synergy.',
    },
    {
      id: 'bl4-b3',
      timeframe: '0:07 - 0:12',
      startSec: 7,
      endSec: 12,
      title: 'Legendary Orange Loot Shower & Weapon Inspect',
      category: 'LOWER_FUNNEL_MONETIZATION',
      tier: 'BOFU',
      ctrLift: 7.2,
      ctiLift: 29.8,
      roas: 3.25,
      description: 'Loot beacon explosion driving Deluxe Season Pass pre-orders and immediate monetization.',
    },
    {
      id: 'bl4-b4',
      timeframe: '0:12 - 0:15',
      startSec: 12,
      endSec: 15,
      title: 'Deluxe Edition Launch Date & Season Pass CTA',
      category: 'BOFU',
      tier: 'BOFU',
      ctrLift: 5.1,
      ctiLift: 17.5,
      roas: 2.95,
      description: 'High-contrast end-card converting accumulated interest into immediate pre-order checkout.',
    },
  ],
};
