import {
  CreativeAsset,
  AttributionModelSummary,
  BAREPersonaEvaluation,
  GamerPersonaProfile,
  ScenarioSimulationResult,
  TelemetryLog,
  ConflictFatigueData,
  ShapleyPreTestAuditData,
} from '@/types';

export const MOCK_CREATIVE_ASSETS: CreativeAsset[] = [

  {
    asset_id: 'asset-apex-s22-trailer',
    campaign_id: 'camp-apex-season-22',
    franchise: 'Apex Legends',
    title: 'Apex Legends: Season 22 Shockwave Gameplay Trailer',
    video_url: '/mock_videos/apex_season_22_preview.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=60',
    duration_sec: 45,
    media_type: 'VIDEO',
    funnel_stage: 'ToFu_Exploration',
    detected_mechanics: [
      {
        mechanic_id: 'mech-01',
        mechanic_name: 'Akimbo Dual-Wield P2020 Gunplay',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.96,
        timestamp_start_sec: 2,
        timestamp_end_sec: 12,
        bounding_box: { x: 22, y: 18, width: 56, height: 64 },
        description: 'Dynamic close-up showcasing high-octane akimbo weapon handling and particle muzzle flares.',
        visual_hook: 'Rapid dual-wielding fire with recoil camera shake',
        audio_cue: 'High-frequency bullet impacts & dynamic bass drop',
      },
      {
        mechanic_id: 'mech-02',
        mechanic_name: 'E-District Neon Cyberpunk Verticality',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.94,
        timestamp_start_sec: 13,
        timestamp_end_sec: 24,
        bounding_box: { x: 10, y: 15, width: 80, height: 70 },
        description: 'Sweeping city panorama featuring gravity lifts, rooftop skirmishes, and holographic billboards.',
        visual_hook: 'Neon skyline zipline transit',
        audio_cue: 'Ambient synthesizer sweep with city sirens',
      },
      {
        mechanic_id: 'mech-03',
        mechanic_name: 'Battle Pass Level 100 Reactive Skin Unlock',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.91,
        timestamp_start_sec: 25,
        timestamp_end_sec: 35,
        bounding_box: { x: 30, y: 25, width: 42, height: 50 },
        description: 'Weapon evolution showcase demonstrating tiered kill-count visual effects on Mozambique reactive skin.',
        visual_hook: 'Reactive lightning particle glow on multi-kill',
        audio_cue: 'Level-up chord progression chime',
      },
      {
        mechanic_id: 'mech-04',
        mechanic_name: 'Limited-Time Heirloom Event Pack Opening',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.89,
        timestamp_start_sec: 36,
        timestamp_end_sec: 45,
        bounding_box: { x: 25, y: 20, width: 50, height: 60 },
        description: 'Loot tick animation sequence opening into Mythic heirloom shards with immediate CTA discount badge.',
        visual_hook: 'Crimson-to-gold loot tick explosion',
        audio_cue: 'Mechanical click into legendary fanfare',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 95, recommendation: 'Optimal hero autoplay unit; high conversion on akimbo hook.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 92, recommendation: 'Twitch drop integration aligns perfectly with Heirloom pack CTA.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 88, recommendation: 'Trim first 12s to focus immediately on Battle Pass reactive skin.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 78, recommendation: 'Resize to 9:16 vertical and add subtitle captions for muted feeds.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 65, recommendation: 'Static keyframe of Reactive Skin is preferable over full video.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 42, recommendation: 'Low text contrast for rapid arena peripheral scanning.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.53, MoFu: 0.24, BoFu: 0.23 },
        dominant_color_palette: ['#0066FF', '#00F5D4', '#FF4655', '#0B0E14'],
        audio_tempo_bpm: 138,
        dialogue_word_count: 42,
        action_density_score: 0.88,
        brand_logo_exposure_sec: 4.8,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-08T14:22:00Z',
  },
  {
    asset_id: 'asset-eafc-toty-promo',
    campaign_id: 'camp-fc25-toty',
    franchise: 'EA Sports FC',
    title: 'EA SPORTS FC 25: Team of the Year Live Campaign',
    video_url: '/mock_videos/fc25_toty_showcase.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=60',
    duration_sec: 30,
    media_type: 'VIDEO',
    funnel_stage: 'BoFu_Conversion',
    detected_mechanics: [
      {
        mechanic_id: 'mech-fc-01',
        mechanic_name: 'HypermotionV Volley Goal & Player Impact Engine',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.95,
        timestamp_start_sec: 1,
        timestamp_end_sec: 8,
        bounding_box: { x: 15, y: 20, width: 70, height: 60 },
        description: 'Broadcast camera capture showing authentic volumetric player physics and top-corner finish.',
        visual_hook: 'Slow-motion net bulge and crowd celebration',
        audio_cue: 'Roaring stadium chant + commentary voiceover',
      },
      {
        mechanic_id: 'mech-fc-02',
        mechanic_name: 'Ultimate Team Walkout Animation - Bellingham TOTY 97 OVR',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.98,
        timestamp_start_sec: 9,
        timestamp_end_sec: 22,
        bounding_box: { x: 20, y: 15, width: 60, height: 70 },
        description: 'Dramatic card flares, gold fireworks, and signature celebration run for 97 OVR TOTY card.',
        visual_hook: 'Gold burst beams and TOTY shield presentation',
        audio_cue: 'Explosive pyrotechnic blast followed by signature orchestral beat',
      },
      {
        mechanic_id: 'mech-fc-03',
        mechanic_name: 'Squad Building Challenge (SBC) Completion Voucher',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.90,
        timestamp_start_sec: 23,
        timestamp_end_sec: 30,
        bounding_box: { x: 28, y: 25, width: 44, height: 50 },
        description: 'Interactive companion app UI showing 88-rated squad submission unlocking guaranteed TOTY loan pack.',
        visual_hook: 'Checkmark completion burst and claim button',
        audio_cue: 'Quick confirmation ping',
      },
    ],
    target_surfaces: [
      { surface: 'STADIUM_BOARDS', compatibility_score: 98, recommendation: 'Flawless pitch-side loop; TOTY gold branding maximizes physical-digital bridge.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 96, recommendation: 'Direct SBC deep-link enables instant in-app conversion.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 94, recommendation: 'High purchase intent conversion on 97 OVR walkout trigger.' },
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 90, recommendation: 'Excellent Friday evening promo takeover unit.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 86, recommendation: 'Great during esports broadcast breaks.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 75, recommendation: 'Good for Halftime pause screen card promos.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.27, MoFu: 0.23, BoFu: 0.50 },
        dominant_color_palette: ['#FFB703', '#0066FF', '#0B0E14', '#FFFFFF'],
        audio_tempo_bpm: 124,
        action_density_score: 0.92,
        brand_logo_exposure_sec: 6.2,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-08T11:05:00Z',
  },
  {
    asset_id: 'asset-bf-redsec-trailer',
    campaign_id: 'camp-bf6-relaunch',
    franchise: 'Battlefield',
    title: 'Battlefield: REDACTED Sector Siege Combat Reel',
    video_url: '/mock_videos/battlefield_siege_reel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=60',
    duration_sec: 40,
    media_type: 'VIDEO',
    funnel_stage: 'ToFu_Exploration',
    detected_mechanics: [
      {
        mechanic_id: 'mech-bf-01',
        mechanic_name: 'Levolution Skybridge Demolition & Dust Storm',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.97,
        timestamp_start_sec: 1,
        timestamp_end_sec: 15,
        bounding_box: { x: 10, y: 10, width: 80, height: 75 },
        description: 'Massive skyscraper bridge structural collapse creating real-time dynamic debris and tactical dust cover.',
        visual_hook: 'Crumbling concrete slabs and cascading glass',
        audio_cue: 'Low-frequency seismic rumble & groaning steel',
      },
      {
        mechanic_id: 'mech-bf-02',
        mechanic_name: 'Armor Squad Tank Flank & Drone Recon',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.92,
        timestamp_start_sec: 16,
        timestamp_end_sec: 28,
        bounding_box: { x: 20, y: 22, width: 60, height: 55 },
        description: 'Coordinated multi-crew tank breaching capture point with thermal optics HUD overlay.',
        visual_hook: 'Thermal vision toggle and target lock pings',
        audio_cue: 'Heavy cannon discharge and radio chatter',
      },
      {
        mechanic_id: 'mech-bf-03',
        mechanic_name: 'Free Access Weekend & Battle Pass Instant Grant',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.88,
        timestamp_start_sec: 29,
        timestamp_end_sec: 40,
        bounding_box: { x: 22, y: 20, width: 56, height: 60 },
        description: 'High-contrast bold typography CTA offering 3-day zero-cost trial and bonus squad cosmetics.',
        visual_hook: 'Flashing FREE WEEKEND neon typography stamp',
        audio_cue: 'Aggressive industrial rock guitar sting',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 96, recommendation: 'Top performer for desktop core FPS conversion.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 91, recommendation: 'High viewer engagement during competitive creator streams.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 82, recommendation: 'Effective in cross-franchise shooter promo slots.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 75, recommendation: 'Focus on vehicle skins for higher store resonance.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 60, recommendation: 'Needs shorter edit for mobile portrait scroll.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 50, recommendation: 'Demolition visuals too complex for brief glance time.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.40, MoFu: 0.30, BoFu: 0.30 },
        dominant_color_palette: ['#FF4655', '#141A24', '#0066FF', '#7A8B99'],
        audio_tempo_bpm: 145,
        action_density_score: 0.96,
        brand_logo_exposure_sec: 5.5,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-07T18:40:00Z',
  },
  {
    asset_id: 'asset-sims-expansion-pack',
    campaign_id: 'camp-sims4-expansion',
    franchise: 'The Sims',
    title: 'The Sims 4: Enchanted Living & Architectural Haven',
    video_url: '/mock_videos/sims_enchanted_haven.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=60',
    duration_sec: 35,
    media_type: 'VIDEO',
    funnel_stage: 'MoFu_Progression',
    detected_mechanics: [
      {
        mechanic_id: 'mech-sims-01',
        mechanic_name: 'Modular Glasshouse Build Mode Time-Lapse',
        funnel_stage: 'ToFu_Exploration',
        confidence_score: 0.97,
        timestamp_start_sec: 1,
        timestamp_end_sec: 14,
        bounding_box: { x: 12, y: 15, width: 76, height: 68 },
        description: 'Speed-build transformation demonstrating curved glass roofs, hanging flora, and custom botanical lighting.',
        visual_hook: 'Fluid snap-to-grid furniture placements',
        audio_cue: 'Whimsical acoustic guitar and upbeat finger snaps',
      },
      {
        mechanic_id: 'mech-sims-02',
        mechanic_name: 'Cozy Gardening & Herbalism Skill Progression',
        funnel_stage: 'MoFu_Progression',
        confidence_score: 0.93,
        timestamp_start_sec: 15,
        timestamp_end_sec: 26,
        bounding_box: { x: 20, y: 20, width: 60, height: 60 },
        description: 'Sim character harvesting rare moonlight mushrooms and crafting scented remedies for neighborhood neighbors.',
        visual_hook: 'Simlish expressive speech bubbles and heart emoticons',
        audio_cue: 'Playful Simlish chatter with bubbly chimes',
      },
      {
        mechanic_id: 'mech-sims-03',
        mechanic_name: 'Bundle & Save 20% Off Launch Discount',
        funnel_stage: 'BoFu_Conversion',
        confidence_score: 0.91,
        timestamp_start_sec: 27,
        timestamp_end_sec: 35,
        bounding_box: { x: 25, y: 22, width: 50, height: 55 },
        description: 'Package showcase highlighting Expansion Pack + Stuff Pack combo pricing with immediate claim link.',
        visual_hook: 'Plumbob emerald glow and discount voucher ribbon',
        audio_cue: 'Signature Sims whimsical chime fanfare',
      },
    ],
    target_surfaces: [
      { surface: 'EA_APP_LAUNCHER', compatibility_score: 97, recommendation: 'Top performing lifestyle campaign placement with high direct checkout rate.' },
      { surface: 'MOBILE_COMPANION', compatibility_score: 92, recommendation: 'High resonance with social & cozy gamers checking catalog on mobile.' },
      { surface: 'IN_GAME_STORE', compatibility_score: 90, recommendation: 'Instant build catalog preview drives immediate DLC impulse buys.' },
      { surface: 'STREAMING_OVERLAYS', compatibility_score: 84, recommendation: 'Great fit for Twitch cozy building streams.' },
      { surface: 'PAUSE_SCREENS', compatibility_score: 72, recommendation: 'High interest when displayed during load screens.' },
      { surface: 'STADIUM_BOARDS', compatibility_score: 25, recommendation: 'Mismatched context for sports arena perimeter displays.' },
    ],
    pydantic_schema_json: {
      schema_version: '2.4.0',
      validator: 'CreativeMetadataSchema',
      asset_type: 'VIDEO_CAMPAIGN',
      extracted_features: {
        funnel_distribution: { ToFu: 0.37, MoFu: 0.35, BoFu: 0.28 },
        dominant_color_palette: ['#00F5D4', '#FFB703', '#A855F7', '#FFFFFF'],
        audio_tempo_bpm: 110,
        action_density_score: 0.65,
        brand_logo_exposure_sec: 4.0,
        direct_response_cta_present: true,
      },
    },
    created_at: '2026-08-08T09:15:00Z',
  },
];

export const MOCK_ATTRIBUTION_SUMMARY: AttributionModelSummary = {
  model_id: 'attr-model-apex-2026-q3',
  franchise: 'Apex Legends',
  updated_at: '2026-08-09T12:00:00Z',
  features: [
    {
      feature_id: 'feat-01',
      feature_name: 'Akimbo Dual-Wield Firefight',
      franchise: 'Apex Legends',
      funnel_stage: 'ToFu_Exploration',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 24,
      roas_impact_y: 2.85,
      quadrant: 'GOLD_MINES',
      confidence: 0.94,
      sample_size: 420000,
      action_recommendation: 'Scale spend by +35% in top 10 DMAs. Creative shows exceptionally low fatigue.',
      description: 'Dynamic twin-weapon combat generates instant viewer retention and high early funnel click-through.',
    },
    {
      feature_id: 'feat-02',
      feature_name: 'E-District Neon Map Exploration',
      franchise: 'Apex Legends',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STREAMING_OVERLAYS',
      frequency_x: 58,
      roas_impact_y: 2.45,
      quadrant: 'CORE_DRIVERS',
      confidence: 0.96,
      sample_size: 890000,
      action_recommendation: 'Maintain continuous flighting; anchor baseline acquisition campaigns.',
      description: 'High aesthetic fidelity and cyberpunk neon palette reliably convert lapsed players.',
    },
    {
      feature_id: 'feat-03',
      feature_name: 'Ranked Ladder Tier Progression Hook',
      franchise: 'Apex Legends',
      funnel_stage: 'MoFu_Progression',
      surface: 'IN_GAME_STORE',
      frequency_x: 88,
      roas_impact_y: 2.10,
      quadrant: 'SATURATED_STARS',
      confidence: 0.92,
      sample_size: 1450000,
      action_recommendation: 'Frequency capping required. Audience fatigue is beginning to depress marginal ROAS.',
      description: 'Competitive grind motivation remains strong but has been over-saturated in programmatic channels.',
    },
    {
      feature_id: 'feat-04',
      feature_name: 'Octane Movement Trick Montage',
      franchise: 'Apex Legends',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STREAMING_OVERLAYS',
      frequency_x: 18,
      roas_impact_y: 1.15,
      quadrant: 'UNTAPPED',
      confidence: 0.88,
      sample_size: 210000,
      action_recommendation: 'Expand A/B test budget by $50k across TikTok and YouTube Shorts.',
      description: 'High viral potential with low current spend. Early signals show promising secondary retention.',
    },
    {
      feature_id: 'feat-05',
      feature_name: 'Battle Pass Level 100 Reactive Skin',
      franchise: 'Apex Legends',
      funnel_stage: 'MoFu_Progression',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 52,
      roas_impact_y: 1.25,
      quadrant: 'WORKHORSES',
      confidence: 0.95,
      sample_size: 780000,
      action_recommendation: 'Optimize audio hooks and pacing to push feature into Core Drivers zone.',
      description: 'Steady dependable conversion among active players; good mid-tier performance.',
    },
    {
      feature_id: 'feat-06',
      feature_name: 'Legend Lore Story Dialogue Clips',
      franchise: 'Apex Legends',
      funnel_stage: 'MoFu_Progression',
      surface: 'MOBILE_COMPANION',
      frequency_x: 82,
      roas_impact_y: 0.85,
      quadrant: 'EFFICIENCY_RISKS',
      confidence: 0.91,
      sample_size: 1100000,
      action_recommendation: 'Trim spend by -25%. Dialogue-heavy creatives suffer steep drop-offs on sound-off mobile feeds.',
      description: 'Lore-heavy audio requires active listening, leading to sub-optimal conversion on muted programmatic feeds.',
    },
    {
      feature_id: 'feat-07',
      feature_name: 'Weapon Charm Micro-Cosmetic Banner',
      franchise: 'Apex Legends',
      funnel_stage: 'BoFu_Conversion',
      surface: 'PAUSE_SCREENS',
      frequency_x: 15,
      roas_impact_y: -0.20,
      quadrant: 'NOISE',
      confidence: 0.79,
      sample_size: 140000,
      action_recommendation: 'Deprecate from creative tag matrix. Statistical noise with no identifiable incremental lift.',
      description: 'Charms lack visual punch and emotional urgency to justify standalone creative focus.',
    },
    {
      feature_id: 'feat-08',
      feature_name: 'Generic 10-Second Countdown Stinger',
      franchise: 'Apex Legends',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STADIUM_BOARDS',
      frequency_x: 48,
      roas_impact_y: -0.65,
      quadrant: 'UNDERPERFORMERS',
      confidence: 0.90,
      sample_size: 620000,
      action_recommendation: 'Pivot creative hook immediately. Replace generic countdown with gameplay highlight.',
      description: 'Abstract countdowns fail to communicate core value proposition before skip button activates.',
    },
    {
      feature_id: 'feat-09',
      feature_name: 'Aggressive Full-Screen Loot Box Pop-Up',
      franchise: 'Apex Legends',
      funnel_stage: 'BoFu_Conversion',
      surface: 'IN_GAME_STORE',
      frequency_x: 85,
      roas_impact_y: -1.35,
      quadrant: 'MONEY_PITS',
      confidence: 0.97,
      sample_size: 1320000,
      action_recommendation: 'Kill immediately. Triggers severe consumer friction and elevates uninstall rate by 4.2%.',
      description: 'Intrusive monetization hooks cause immediate user resistance, confirmed by BARE persona simulations.',
    },
    // FC25 features
    {
      feature_id: 'feat-10',
      feature_name: 'TOTY Walkout 97 OVR Card Reveal',
      franchise: 'EA Sports FC',
      funnel_stage: 'BoFu_Conversion',
      surface: 'IN_GAME_STORE',
      frequency_x: 28,
      roas_impact_y: 3.20,
      quadrant: 'GOLD_MINES',
      confidence: 0.98,
      sample_size: 950000,
      action_recommendation: 'Scale aggressively during 7-day TOTY promo window. Massive high-intent whale engagement.',
      description: 'Walkout fireworks and highest-tier player stats produce peak D7 ROAS multiplier.',
    },
    {
      feature_id: 'feat-11',
      feature_name: 'HypermotionV Volley Goal & Net Physics',
      franchise: 'EA Sports FC',
      funnel_stage: 'ToFu_Exploration',
      surface: 'STADIUM_BOARDS',
      frequency_x: 62,
      roas_impact_y: 2.60,
      quadrant: 'CORE_DRIVERS',
      confidence: 0.95,
      sample_size: 1200000,
      action_recommendation: 'Maintain top-of-funnel presence across broadcast and pitch perimeter inventory.',
      description: 'Photorealistic match realism drives strong organic interest among football enthusiasts.',
    },
    // Battlefield features
    {
      feature_id: 'feat-12',
      feature_name: 'Levolution Skybridge Collapse Action',
      franchise: 'Battlefield',
      funnel_stage: 'ToFu_Exploration',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 22,
      roas_impact_y: 2.70,
      quadrant: 'GOLD_MINES',
      confidence: 0.93,
      sample_size: 380000,
      action_recommendation: 'Scale up desktop hero placements ahead of Season 8 launch.',
      description: 'Destructible environments highlight key technological differentiator versus competitor arcade shooters.',
    },
    // The Sims features
    {
      feature_id: 'feat-13',
      feature_name: 'Modular Glasshouse Build Time-Lapse',
      franchise: 'The Sims',
      funnel_stage: 'MoFu_Progression',
      surface: 'EA_APP_LAUNCHER',
      frequency_x: 26,
      roas_impact_y: 2.50,
      quadrant: 'GOLD_MINES',
      confidence: 0.94,
      sample_size: 450000,
      action_recommendation: 'Increase allocation in high gamer density metropolitan corridors.',
      description: 'Satisfying construction time-lapses produce very high catalog browse and bundle conversion.',
    },
  ],
  gemini_cot_reasoning: {
    thinking_level: 'HIGH',
    model: 'gemini-3.6-flash',
    executive_summary: 'Econometric SHAP analysis identifies an extreme efficiency bifurcation: gameplay mechanics with high visceral kinetic feedback (Akimbo Firefights, Volley Physics, Levolution Destruction) yield marginal ROAS between 2.45x and 3.20x, occupying the Gold Mines and Core Drivers quadrants. Conversely, aggressive direct-conversion pop-ups and abstract stingers represent Money Pits and Underperformers (-0.65x to -1.35x ROAS), triggering severe consumer backlash.',
    key_drivers: [
      'Kinetic gameplay mechanics deliver +142% higher marginal conversion than pre-rendered CGI cutscenes.',
      'Surface synergy: EA App Launcher combined with ToFu exploration hooks achieves lowest blended CPI ($3.85 vs $6.10 average).',
      'TOTY and Seasonal Reactive cosmetic milestones produce sharp 48-hour ROAS spikes with minimal decay.',
    ],
    risk_factors: [
      'Ranked Ladder Progression features have reached 88% market saturation frequency; marginal ROAS is dropping at -0.12x per $100k added spend.',
      'Dialogue-driven lore clips on mobile feeds suffer 68% view abandonment within 3 seconds due to muted autoplay defaults.',
      'Intrusive store modals generate +4.2% elevated churn among Casual Socializer personas.',
    ],
    strategic_action_plan: [
      {
        action: 'Reallocate $350k from Money Pits (Loot Modals) to Gold Mines (Akimbo & Levolution)',
        expected_lift: '+24.6% Blended D7 ROAS',
        rationale: 'Shifting spend up the steep initial portion of the Hill saturation curve captures unsaturated marginal return.',
      },
      {
        action: 'Apply Frequency Cap of 3 impressions/week to Saturated Stars (Ranked Progression)',
        expected_lift: '-18.2% Waste Reduction',
        rationale: 'Prevents creative fatigue from causing negative cohort retention.',
      },
      {
        action: 'Inject Visual Captions & Rapid 1.2s Kinetic Opening to Dialogue Creatives',
        expected_lift: '+0.45x mROAS Pivot',
        rationale: 'Recovers mobile companion and social feed audiences without sacrificing narrative appeal.',
      },
    ],
    thinking_trace: [
      '1. Ingesting SHAP attribution vector across 13 cross-franchise creative features and 6 surfaces...',
      '2. Calculating 2nd-order derivatives for Hill saturation curvature: verifying equimarginal equalization point across channels...',
      '3. Cross-referencing BARE persona friction monologues with negative SHAP outliers: confirming Loot Box Modal causes active churn resistance...',
      '4. Applying 20% daily pacing clamp constraint to prevent volatile media spend displacement...',
      '5. Synthesizing final strategic guidance for executive review with Brian Baron & Christina Bumbaca.',
    ],
  },
};

export const MOCK_GAMER_PROFILES: GamerPersonaProfile[] = [
  {
    persona_id: 'persona-grinder',
    archetype: 'COMPETITIVE_GRINDER',
    name: 'Alex "Viper" Chen',
    age_range: '19-24',
    income_tier: '$35k - $55k',
    preferred_franchise: 'Apex Legends',
    gaming_hours_weekly: 34,
    price_sensitivity_score: 45,
    competitive_drive: 96,
    lore_immersion: 30,
    social_connection: 75,
    monetization_affinity: 60,
    avatar_url: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&auto=format&fit=crop&q=60',
    description: 'High-skill ranked warrior focused strictly on tick-rate, gun meta, rank RP progression, and exclusive high-tier skill rewards.',
  },
  {
    persona_id: 'persona-lore',
    archetype: 'LORE_SEEKER',
    name: 'Elena Rostova',
    age_range: '26-32',
    income_tier: '$65k - $90k',
    preferred_franchise: 'Battlefield',
    gaming_hours_weekly: 16,
    price_sensitivity_score: 55,
    competitive_drive: 40,
    lore_immersion: 95,
    social_connection: 60,
    monetization_affinity: 45,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=60',
    description: 'Deep worldbuilding enthusiast invested in character backstories, environmental storytelling, narrative campaigns, and authentic military realism.',
  },
  {
    persona_id: 'persona-socializer',
    archetype: 'CASUAL_SOCIALIZER',
    name: 'Marcus Brody',
    age_range: '22-29',
    income_tier: '$50k - $75k',
    preferred_franchise: 'The Sims',
    gaming_hours_weekly: 10,
    price_sensitivity_score: 80,
    competitive_drive: 20,
    lore_immersion: 70,
    social_connection: 92,
    monetization_affinity: 35,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=60',
    description: 'Weekend social gamer seeking low-stress creative expression, multiplayer chill sessions with friends, and cozy architectural aesthetics.',
  },
  {
    persona_id: 'persona-whale',
    archetype: 'ULTIMATE_TEAM_WHALE',
    name: 'Julian Sterling',
    age_range: '28-38',
    income_tier: '$140k - $220k',
    preferred_franchise: 'EA Sports FC',
    gaming_hours_weekly: 22,
    price_sensitivity_score: 15,
    competitive_drive: 88,
    lore_immersion: 25,
    social_connection: 85,
    monetization_affinity: 98,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=60',
    description: 'High-disposable-income football fanatic dedicated to assembling premier 95+ OVR squads during TOTY promo drops regardless of pack price.',
  },
];

export const MOCK_BARE_EVALUATIONS: Record<string, BAREPersonaEvaluation> = {
  'persona-grinder': {
    persona_id: 'persona-grinder',
    archetype: 'COMPETITIVE_GRINDER',
    base_pass: {
      model: 'base-llama3-70b-raw-unaligned',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: `Look, the akimbo P2020s look sick in the trailer, but are you actually fixing the audio footsteps on E-District? If Horizon can still silent-drop on my head from height, I don't care about a $20 reactive Mozambique skin. Also, why is the ranked entry cost 60 RP in Platinum? That's ridiculous grind inflation. If they don't buff the ranked progression curve, I'm just sticking to scrims and not buying the battle pass until level 100.`,
      detected_objections: [
        'Audio engine desync & silent vertical footsteps skepticism',
        'Ranked RP grind inflation perceived as predatory engagement padding',
        'Battle pass purchase withheld until completion certainty',
      ],
      sentiment_score: -0.15,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'WISHLIST_ADD',
        confidence: 0.86,
        willingness_to_pay_usd: 10.0,
        churn_risk_probability: 0.22,
        conversion_probability: 0.68,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 88,
        visual_fidelity: 90,
        pricing_fairness: 52,
        fomo_intensity: 74,
        community_trust: 46,
      },
      friction_mitigation_notes: 'Emphasize competitive server tick-rate stability and weapon balancing patch notes in mid-funnel copy rather than cosmetic prices.',
    },
  },
  'persona-lore': {
    persona_id: 'persona-lore',
    archetype: 'LORE_SEEKER',
    base_pass: {
      model: 'base-llama3-70b-raw-unaligned',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: `The skyscraper collapse looks like classic Battlefield, but is there actual narrative weight to this conflict or is it just generic red-versus-blue again? I loved the environmental lore in BF1. If this season has world events that evolve the map lore week-to-week, I'm all in. But if it's just another cosmetic shop refresh with zero story cinematics, it feels hollow.`,
      detected_objections: [
        'Desire for narrative-driven world evolution rather than static cosmetic refreshes',
        'Skepticism of emotional depth in live service multiplayer',
      ],
      sentiment_score: 0.35,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.82,
        willingness_to_pay_usd: 29.99,
        churn_risk_probability: 0.15,
        conversion_probability: 0.79,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 78,
        visual_fidelity: 94,
        pricing_fairness: 72,
        fomo_intensity: 60,
        community_trust: 80,
      },
      friction_mitigation_notes: 'Highlight environmental lore codex unlocks and episodic story beat missions in narrative social teasers.',
    },
  },
  'persona-socializer': {
    persona_id: 'persona-socializer',
    archetype: 'CASUAL_SOCIALIZER',
    base_pass: {
      model: 'base-llama3-70b-raw-unaligned',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: `The glasshouse plants are adorable! But $39.99 for an expansion pack when I already spent $300 on past packs feels really steep right now. My friends and I just want cute building items. If this goes on sale for $29.99 or comes bundled with the gardening stuff pack, I'll grab it immediately for our weekend build challenge.`,
      detected_objections: [
        'High cumulative pack price fatigue ($300+ historical spend)',
        'Immediate price resistance at full $39.99 MSRP',
        'Seeking bundle discount synergy with friends',
      ],
      sentiment_score: 0.10,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'WISHLIST_ADD',
        confidence: 0.91,
        willingness_to_pay_usd: 24.99,
        churn_risk_probability: 0.18,
        conversion_probability: 0.74,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 82,
        visual_fidelity: 89,
        pricing_fairness: 44,
        fomo_intensity: 55,
        community_trust: 68,
      },
      friction_mitigation_notes: 'Deploy 20% bundle discount messaging in EA App Launcher to trigger immediate checkout conversion.',
    },
  },
  'persona-whale': {
    persona_id: 'persona-whale',
    archetype: 'ULTIMATE_TEAM_WHALE',
    base_pass: {
      model: 'base-llama3-70b-raw-unaligned',
      entropy: 'HIGH_ENTROPY_UNALIGNED',
      raw_friction_monologue: `97 Bellingham with Anticipate+ and Power Shot+ is a must-have for Weekend League. I don't care about spending 12,000 FC Points on Friday 6 PM drop, but what are the untradeable pack odds? If the pack weight is 0.01% again like last year, Reddit is going to explode with pitchforks. Make sure there are guaranteed rating SBCs so opening 50 packs doesn't feel like a complete waste of fodder.`,
      detected_objections: [
        'Pack weight transparency and probability threshold scrutiny',
        'Fear of zero-value fodder accumulation without high-tier SBC sinks',
        'Sensitivity to community sentiment / Reddit backlash',
      ],
      sentiment_score: 0.60,
    },
    refine_pass: {
      model: 'gemini-3.6-flash',
      entropy: 'LOW_ENTROPY_DETERMINISTIC',
      pydantic_schema_enforced: true,
      buyer_action: {
        action: 'INSTANT_PURCHASE',
        confidence: 0.97,
        willingness_to_pay_usd: 199.99,
        churn_risk_probability: 0.08,
        conversion_probability: 0.96,
        fsm_transition_valid: true,
      },
      radar_resonance: {
        gameplay_excitement: 95,
        visual_fidelity: 96,
        pricing_fairness: 65,
        fomo_intensity: 98,
        community_trust: 58,
      },
      friction_mitigation_notes: 'Highlight high-rated duplicate storage and repeatable TOTY crafting upgrades alongside store pack releases.',
    },
  },
};

export const INITIAL_TELEMETRY_LOGS: TelemetryLog[] = [
  {
    id: 'log-01',
    timestamp: '13:14:02.120',
    source: 'ADK_TAGGING_AGENT',
    level: 'INFO',
    message: 'Ingested asset_apex_s22_trailer.mp4 (45.0s, 1080p60). Initiating 1fps frame decimation...',
    payload: { fps_sampled: 45, audio_channels: 2, resolution: '1920x1080' },
  },
  {
    id: 'log-02',
    timestamp: '13:14:03.480',
    source: 'ADK_TAGGING_AGENT',
    level: 'SUCCESS',
    message: 'gemini-3.6-flash structured output validated against CreativeMetadataSchema. 4 mechanics detected.',
    payload: { mechanics_count: 4, dominant_funnel: 'ToFu_Exploration', confidence: 0.94 },
  },
  {
    id: 'log-03',
    timestamp: '13:14:04.910',
    source: 'ADK_ANALYTICS_AGENT',
    level: 'INFO',
    message: 'Executing Meridian MMM Bayesian prior tuning against BigQuery causal lift experiments...',
    payload: { dataset: 'ea_measurement.dim_metro_geospine', causal_trials: 48 },
  },
  {
    id: 'log-04',
    timestamp: '13:14:05.620',
    source: 'ADK_ANALYTICS_AGENT',
    level: 'SUCCESS',
    message: 'Tactical 9-Grid generated. 4 Gold Mines, 3 Core Drivers, 1 Money Pit isolated.',
    payload: { top_feature: 'Akimbo Dual-Wield Firefight', mROAS: 2.85 },
  },
  {
    id: 'log-05',
    timestamp: '13:14:07.100',
    source: 'BARE_PERSONA_AGENT',
    level: 'INFO',
    message: 'Running DeepSona BARE simulation (Base pass unaligned -> Refine pass Pydantic FSM) on 4 archetypes...',
  },
  {
    id: 'log-06',
    timestamp: '13:14:08.350',
    source: 'BARE_PERSONA_AGENT',
    level: 'SUCCESS',
    message: 'BARE evaluations complete: Competitive Grinder (Wishlist), Whale (Instant Purchase $199.99).',
    payload: { mean_conversion_prob: 0.79, mean_churn_risk: 0.16 },
  },
  {
    id: 'log-07',
    timestamp: '13:14:09.800',
    source: 'A2UI_DISPATCHER',
    level: 'EXECUTION',
    message: 'Streaming A2UI surface payload createSurface id="surface-exec-overview" to Next.js client.',
    payload: { widget_catalog: ['a2ui-metric-card', 'a2ui-bar-chart', 'a2ui-scurve-chart'] },
  },
];

export const MOCK_CONFLICT_FATIGUE_OCT24_27: ConflictFatigueData = {
  target_campaign_id: 'camp-fc27-toty-001',
  target_campaign_name: 'EA FC 27 TOTY Mid-Season Push',
  conflicting_campaign_id: 'camp-apex-s26-002',
  conflicting_campaign_name: 'Apex Legends Season 26 Launch',
  target_franchise: 'EA Sports FC',
  conflicting_franchise: 'Apex Legends',
  flight_start: '2026-10-24',
  flight_end: '2026-10-27',
  shared_ea_id_overlap_pct: 42.1,
  shared_player_count: 1280000,
  ad_fatigue_suppression_penalty_pct: 14.5,
  net_bookings_risk_usd: 420000,
  recommended_timeline_shift_days: 3,
  mitigated_flight_start: '2026-10-27',
  mitigated_flight_end: '2026-11-07',
  projected_net_bookings_recovery_usd: 420000,
  baseline_net_bookings_usd: 4710000,
  unmitigated_net_bookings_usd: 4290000,
  post_mitigation_net_bookings_usd: 5130000,
  projected_installs: 364000,
  blended_cpi_usd: 4.12,
  day7_roas: 3.42,
  mitigation_strategy: 'Timeline shift (+3 days) to Oct 27-Nov 07 & negative audience suppression on heavy Apex players',
  status: 'AMBER_COLLISION_DETECTED',
};

export const MOCK_BELLINGHAM_SHAPLEY_AUDIT: ShapleyPreTestAuditData = {
  franchise: 'EA Sports FC',
  asset_title: 'EA SPORTS FC 27 - Official Gameplay Trailer (15s Pre-Test)',
  comparison_pair: 'FUT Pack Walkout Jude Bellingham vs Skill Move / Trick Shot Showcase',
  funnel_balance_index: 0.74,
  top_of_funnel_score: 41.0,
  lower_funnel_score: 32.4,
  predicted_d7_roas: 3.42,
  audit_verdict: 'BALANCED_HIGH_POTENTIAL',
  prescriptive_action: 'Deploy Trick Shot hook in 0:00-0:03 for viral thumb-stop (+41.0% CTR), bridge gameplay progression at 0:03-0:08, and transition to Jude Bellingham Walkout at 0:08-0:15 for high CTI monetization (+32.4% CTI / 3.42x ROAS).',
  recommended_edit: 'Sequence 9:16 vertical cut with trick-shot intro into Bellingham gold walkout climax.',
  features: [
    {
      feature_name: 'FUT Pack Walkout Jude Bellingham',
      category: 'LOWER_FUNNEL_MONETIZATION',
      funnel_tier: 'BOFU',
      marginal_ctr_lift_pct: 4.2,
      marginal_cti_lift_pct: 32.4,
      marginal_d7_roas_multiplier: 3.42,
      confidence_score: 0.96,
      description: 'High intent, high-converting walkout animation hook driving direct in-game store conversions.',
      timestamp_start_sec: 7,
      timestamp_end_sec: 12,
    },
    {
      feature_name: 'Skill Move / Trick Shot Showcase',
      category: 'TOP_OF_FUNNEL',
      funnel_tier: 'TOFU',
      marginal_ctr_lift_pct: 41.0,
      marginal_cti_lift_pct: -12.1,
      marginal_d7_roas_multiplier: 1.85,
      confidence_score: 0.94,
      description: 'Viral stopping power and high click-through rate, but lower day-7 conversion efficiency.',
      timestamp_start_sec: 0,
      timestamp_end_sec: 3,
    },
  ],
  storybeats: [
    {
      id: 'fc-b1',
      timeframe: '0:00 - 0:03',
      startSec: 0,
      endSec: 3,
      title: 'Skill Move / Trick Shot Showcase',
      category: 'TOP_OF_FUNNEL',
      tier: 'TOFU',
      ctrLift: 41.0,
      ctiLift: -12.1,
      roas: 1.85,
      description: 'Viral stopping power and high click-through rate thumb-stop hook capturing immediate TikTok & Reels attention.',
    },
    {
      id: 'fc-b2',
      timeframe: '0:03 - 0:07',
      startSec: 3,
      endSec: 7,
      title: 'HypermotionV Volley Goal Physics',
      category: 'NEUTRAL_ENGAGEMENT',
      tier: 'MOFU',
      ctrLift: 15.2,
      ctiLift: 4.1,
      roas: 2.20,
      description: 'Photorealistic match gameplay bridge connecting viral trick hook into authentic match intensity.',
    },
    {
      id: 'fc-b3',
      timeframe: '0:07 - 0:12',
      startSec: 7,
      endSec: 12,
      title: 'FUT Pack Walkout Jude Bellingham (97 OVR)',
      category: 'LOWER_FUNNEL_MONETIZATION',
      tier: 'BOFU',
      ctrLift: 4.2,
      ctiLift: 32.4,
      roas: 3.42,
      description: 'High intent, high-converting walkout animation hook driving direct Ultimate Team in-game store conversions.',
    },
    {
      id: 'fc-b4',
      timeframe: '0:12 - 0:15',
      startSec: 12,
      endSec: 15,
      title: 'Pre-Order / TOTY Live End Card CTA',
      category: 'BOFU',
      tier: 'BOFU',
      ctrLift: 5.0,
      ctiLift: 18.0,
      roas: 3.10,
      description: 'Direct response closing unit converting accumulated intent with limited-time loan player pack incentive.',
    },
  ],
};

export const MOCK_APEX_SHAPLEY_AUDIT: ShapleyPreTestAuditData = {
  franchise: 'Apex Legends',
  asset_title: 'Apex Legends Season 26 - Launch Trailer (15s Pre-Test)',
  comparison_pair: 'Apex Mythic Heirloom Inspect vs Apex Superglide / Tap-Strafe',
  funnel_balance_index: 0.76,
  top_of_funnel_score: 38.0,
  lower_funnel_score: 28.5,
  predicted_d7_roas: 3.15,
  audit_verdict: 'BALANCED_HIGH_POTENTIAL',
  prescriptive_action: 'Open with Superglide movement clip in first 3 seconds (0:00-0:03) for viral thumb-stop (+38.0% CTR), bridge tactical team coordination at 0:03-0:08, and close with Mythic Heirloom Inspect and event CTA at 0:08-0:15 (+28.5% CTI / 3.15x ROAS).',
  recommended_edit: 'Combine high-octane movement gameplay hook with mythic heirloom inspect payoff.',
  features: [
    {
      feature_name: 'Apex Mythic Heirloom Inspect',
      category: 'LOWER_FUNNEL_MONETIZATION',
      funnel_tier: 'BOFU',
      marginal_ctr_lift_pct: 6.5,
      marginal_cti_lift_pct: 28.5,
      marginal_d7_roas_multiplier: 3.15,
      confidence_score: 0.95,
      description: 'Premium cosmetic showcase driving high-tier pack purchases and immediate monetization.',
      timestamp_start_sec: 7,
      timestamp_end_sec: 12,
    },
    {
      feature_name: 'Apex Superglide / Tap-Strafe',
      category: 'TOP_OF_FUNNEL',
      funnel_tier: 'TOFU',
      marginal_ctr_lift_pct: 38.0,
      marginal_cti_lift_pct: -9.0,
      marginal_d7_roas_multiplier: 1.92,
      confidence_score: 0.92,
      description: 'High-velocity movement mechanics capturing immediate gamer attention and driving top-of-funnel CTR.',
      timestamp_start_sec: 0,
      timestamp_end_sec: 3,
    },
  ],
  storybeats: [
    {
      id: 'apex-b1',
      timeframe: '0:00 - 0:03',
      startSec: 0,
      endSec: 3,
      title: 'Apex Superglide / Tap-Strafe Movement Hook',
      category: 'TOP_OF_FUNNEL',
      tier: 'TOFU',
      ctrLift: 38.0,
      ctiLift: -9.0,
      roas: 1.92,
      description: 'High-velocity movement mechanics capturing immediate competitive gamer attention and driving top-of-funnel CTR.',
    },
    {
      id: 'apex-b2',
      timeframe: '0:03 - 0:07',
      startSec: 3,
      endSec: 7,
      title: 'Tactical Map Ping & Squad Coordination',
      category: 'NEUTRAL_ENGAGEMENT',
      tier: 'MOFU',
      ctrLift: 12.0,
      ctiLift: 8.5,
      roas: 2.45,
      description: 'Squad communication showcase bridging kinetic movement into cooperative strategy and team synergy.',
    },
    {
      id: 'apex-b3',
      timeframe: '0:07 - 0:12',
      startSec: 7,
      endSec: 12,
      title: 'Apex Mythic Heirloom Inspect Animation',
      category: 'LOWER_FUNNEL_MONETIZATION',
      tier: 'BOFU',
      ctrLift: 6.5,
      ctiLift: 28.5,
      roas: 3.15,
      description: 'Premium cosmetic inspection driving high-tier pack purchases, event shard engagement, and immediate monetization.',
    },
    {
      id: 'apex-b4',
      timeframe: '0:12 - 0:15',
      startSec: 12,
      endSec: 15,
      title: 'Season 26 Launch Date & Free Play CTA',
      category: 'BOFU',
      tier: 'BOFU',
      ctrLift: 4.0,
      ctiLift: 15.0,
      roas: 2.80,
      description: 'High-contrast end-card converting accumulated interest into immediate battle pass activation.',
    },
  ],
};

