"""Equimarginal Hill Saturation Optimization Engine.

Implements the authentic Equimarginal principle across multi-channel marketing portfolios
subject to Hill saturation response curves, strict 20% daily pacing shift clamps,
and zero-sum reallocation portfolio constraints.
"""

import time
import numpy as np
from typing import List, Dict, Tuple, Optional
from scipy.optimize import minimize, Bounds, LinearConstraint

from app.schemas.meridian import (
    ChannelSpendConstraint,
    EquimarginalOptimizationRequest,
    EquimarginalOptimizationResponse,
    ChannelOptimizationResult,
    SCurvePoint,
)


class EquimarginalPacingEngine:
    """Mathematical optimizer for multi-channel Hill Saturation budget allocation."""

    @staticmethod
    def hill_revenue(spend: float, base_roas: float, s: float, k: float) -> float:
        """Calculate total revenue from Hill saturation curve.

        R(x) = base_roas * (x^k / (x^k + s^k)) * s
        Where s is half-saturation spend, k is shape parameter.
        """
        if spend <= 0:
            return 0.0
        x_k = spend ** k
        s_k = s ** k
        # Total revenue generated by spend x
        # Note: Scaled by half-saturation spend s so that dimensions match currency
        return base_roas * s * (x_k / (x_k + s_k))

    @staticmethod
    def marginal_roas(spend: float, base_roas: float, s: float, k: float) -> float:
        """Calculate marginal ROAS (derivative of revenue with respect to spend).

        mROAS(x) = base_roas * (s^k * k * x^(k-1)) / (x^k + s^k)^2 * s
        """
        if spend <= 1e-6:
            # Near zero spend, evaluate limit as x -> 0+
            # For k > 1, mROAS(0) = 0. For k = 1, mROAS(0) = base_roas / s
            spend = 1e-6
        x_k = spend ** k
        s_k = s ** k
        numerator = base_roas * s * s_k * k * (spend ** (k - 1))
        denominator = (x_k + s_k) ** 2
        if denominator <= 0:
            return 0.0
        return numerator / denominator

    @staticmethod
    def average_roas(spend: float, revenue: float) -> float:
        """Calculate average ROAS = Revenue / Spend."""
        if spend <= 0:
            return 0.0
        return revenue / spend

    def generate_s_curve(
        self,
        base_roas: float,
        s: float,
        k: float,
        current_spend: float,
        num_points: int = 50,
    ) -> List[SCurvePoint]:
        """Generate high-resolution S-curve points from 0 to 2.5x current spend."""
        max_spend = max(current_spend * 2.5, s * 2.0, 10000.0)
        spends = np.linspace(max(100.0, current_spend * 0.05), max_spend, num_points)

        points = []
        for sp in spends:
            rev = self.hill_revenue(float(sp), base_roas, s, k)
            m_roas = self.marginal_roas(float(sp), base_roas, s, k)
            avg_r = self.average_roas(float(sp), rev)
            points.append(
                SCurvePoint(
                    spend=round(float(sp), 2),
                    roas=round(float(avg_r), 4),
                    marginal_roas=round(float(m_roas), 4),
                    projected_revenue=round(float(rev), 2),
                )
            )
        return points

    def solve(
        self, request: EquimarginalOptimizationRequest
    ) -> EquimarginalOptimizationResponse:
        """Execute Equimarginal optimization solving for optimal channel spend allocations."""
        start_time = time.perf_counter()

        channels = request.channels
        n = len(channels)
        if n == 0:
            raise ValueError("Optimization requires at least 1 channel constraint")

        current_spends = np.array([ch.current_spend for ch in channels], dtype=np.float64)
        total_current_budget = float(np.sum(current_spends))

        target_total_budget = (
            request.total_budget
            if request.total_budget is not None and request.total_budget > 0
            else total_current_budget
        )

        max_shift_pct = request.max_daily_shift_pct  # e.g., 0.20 for 20% clamp

        # Compute lower and upper bounds for each channel
        lower_bounds = []
        upper_bounds = []
        for i, ch in enumerate(channels):
            # 20% daily pacing clamp constraint: 0.80 * x_i <= x_i* <= 1.20 * x_i
            pacing_min = ch.current_spend * (1.0 - max_shift_pct)
            pacing_max = ch.current_spend * (1.0 + max_shift_pct)

            # Combine with user-defined min/max if provided
            lb = max(0.0, pacing_min)
            if ch.min_spend is not None:
                lb = max(lb, ch.min_spend)

            ub = pacing_max
            if ch.max_spend is not None:
                ub = min(ub, ch.max_spend)

            if lb > ub:
                # If constraints conflict, prioritize pacing clamp
                lb = min(pacing_min, pacing_max)
                ub = max(pacing_min, pacing_max)

            lower_bounds.append(lb)
            upper_bounds.append(ub)

        lower_bounds = np.array(lower_bounds, dtype=np.float64)
        upper_bounds = np.array(upper_bounds, dtype=np.float64)

        # Ensure target budget is feasible within sum of bounds
        min_total = float(np.sum(lower_bounds))
        max_total = float(np.sum(upper_bounds))

        feasible_budget = np.clip(target_total_budget, min_total, max_total)

        # Objective function: Negative Total Portfolio Revenue
        def objective(x):
            tot_rev = 0.0
            for i, ch in enumerate(channels):
                tot_rev += self.hill_revenue(
                    float(x[i]), ch.base_roas, ch.half_saturation_s, ch.hill_slope_k
                )
            return -tot_rev

        # Gradient of objective for fast convergence
        def gradient(x):
            grads = np.zeros(n, dtype=np.float64)
            for i, ch in enumerate(channels):
                grads[i] = -self.marginal_roas(
                    float(x[i]), ch.base_roas, ch.half_saturation_s, ch.hill_slope_k
                )
            return grads

        # Zero-Sum / Total Budget Equality Constraint: sum(x) = feasible_budget
        budget_constraint = LinearConstraint(
            np.ones((1, n)), [feasible_budget], [feasible_budget]
        )

        bounds = Bounds(lower_bounds, upper_bounds)

        # Initial guess: current spend scaled to feasible budget
        if total_current_budget > 0:
            x0 = current_spends * (feasible_budget / total_current_budget)
        else:
            x0 = np.full(n, feasible_budget / n)
        x0 = np.clip(x0, lower_bounds, upper_bounds)
        # Re-normalize x0 to satisfy sum exactly
        if np.sum(x0) > 0:
            x0 = x0 * (feasible_budget / np.sum(x0))
            x0 = np.clip(x0, lower_bounds, upper_bounds)

        # Run SLSQP optimization
        res = minimize(
            objective,
            x0,
            jac=gradient,
            method="SLSQP",
            bounds=bounds,
            constraints=[budget_constraint],
            options={"maxiter": 200, "ftol": 1e-9, "disp": False},
        )

        allocated_spends = res.x

        # Enforce exact sum reconciliation (within $0.01 precision)
        sum_alloc = float(np.sum(allocated_spends))
        residual = feasible_budget - sum_alloc
        if abs(residual) > 1e-4:
            # Distribute residual proportionally to channels not pegged at bounds
            slack = upper_bounds - allocated_spends
            if np.sum(slack) > 0:
                allocated_spends += residual * (slack / np.sum(slack))
            else:
                allocated_spends[0] += residual

        # Calculate results per channel
        channel_results: List[ChannelOptimizationResult] = []
        total_proj_revenue = 0.0
        max_shift_observed = 0.0

        for i, ch in enumerate(channels):
            alloc = float(allocated_spends[i])
            curr = float(ch.current_spend)
            delta = alloc - curr
            delta_pct = (delta / curr) if curr > 0 else 0.0
            max_shift_observed = max(max_shift_observed, abs(delta_pct))

            proj_rev = self.hill_revenue(
                alloc, ch.base_roas, ch.half_saturation_s, ch.hill_slope_k
            )
            total_proj_revenue += proj_rev

            m_roas = self.marginal_roas(
                alloc, ch.base_roas, ch.half_saturation_s, ch.hill_slope_k
            )
            avg_r = self.average_roas(alloc, proj_rev)

            # Estimate installs based on CPI proxy ($35 baseline)
            est_cpi = max(12.0, 35.0 / max(0.5, avg_r))
            proj_installs = int(alloc / est_cpi) if est_cpi > 0 else 0

            s_curve = self.generate_s_curve(
                ch.base_roas, ch.half_saturation_s, ch.hill_slope_k, curr, num_points=40
            )

            channel_results.append(
                ChannelOptimizationResult(
                    channel=ch.channel,
                    current_spend=round(curr, 2),
                    allocated_spend=round(alloc, 2),
                    spend_delta=round(delta, 2),
                    spend_delta_pct=round(delta_pct, 4),
                    marginal_roas=round(m_roas, 4),
                    projected_roas=round(avg_r, 4),
                    projected_revenue=round(proj_rev, 2),
                    projected_installs=proj_installs,
                    s_curve_points=s_curve,
                )
            )

        # Baseline revenue under current allocation
        baseline_revenue = 0.0
        for ch in channels:
            baseline_revenue += self.hill_revenue(
                ch.current_spend, ch.base_roas, ch.half_saturation_s, ch.hill_slope_k
            )

        rev_uplift_pct = (
            ((total_proj_revenue - baseline_revenue) / baseline_revenue * 100.0)
            if baseline_revenue > 0
            else 0.0
        )

        total_alloc_budget = float(np.sum(allocated_spends))
        net_delta = total_alloc_budget - total_current_budget
        zero_sum_satisfied = abs(net_delta) < 0.10 or not request.enforce_zero_sum
        pacing_clamp_satisfied = max_shift_observed <= (max_shift_pct + 0.01)

        portfolio_d7_roas = (
            (total_proj_revenue / total_alloc_budget) if total_alloc_budget > 0 else 0.0
        )
        total_installs = sum(cr.projected_installs for cr in channel_results)
        portfolio_cpi = (
            (total_alloc_budget / total_installs) if total_installs > 0 else 28.50
        )

        latency_ms = (time.perf_counter() - start_time) * 1000.0

        return EquimarginalOptimizationResponse(
            scenario_id=f"scen-{int(time.time())}",
            campaign_id=request.campaign_id,
            franchise=request.franchise,
            total_current_budget=round(total_current_budget, 2),
            total_allocated_budget=round(total_alloc_budget, 2),
            budget_net_delta=round(net_delta, 4),
            total_projected_revenue=round(total_proj_revenue, 2),
            portfolio_d7_roas=round(portfolio_d7_roas, 4),
            portfolio_cpi=round(portfolio_cpi, 2),
            revenue_uplift_pct=round(rev_uplift_pct, 2),
            zero_sum_satisfied=zero_sum_satisfied,
            pacing_clamp_satisfied=pacing_clamp_satisfied,
            max_shift_observed_pct=round(max_shift_observed * 100.0, 2),
            channel_allocations=channel_results,
            solver_latency_ms=round(latency_ms, 2),
            convergence_status="OPTIMAL_CONVERGED" if res.success else "APPROX_CONVERGED",
        )


pacing_engine = EquimarginalPacingEngine()
